### ISSUE TITLE
BCF bug in Bonsai (0.8.4-alpha251104)

### ISSUE THREAD

**Issue by PahlawanJoey** [IfcOpenShell/IfcOpenShell#7318]
### Bug Description

```
os: Windows
os_version: 10.0.26100
python_version: 3.11.11
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 198 Stepping 2, GenuineIntel
blender_version: 4.5.3 LTS
bonsai_version: 0.8.4-alpha251104
bonsai_commit_hash: aeed371
bonsai_commit_date: 2025-11-04T19:24:22+05:00
last_actions: 
last_error: None
ifc: Vebo Beton.ifc
schema: IFC2X3
preprocessor_version: IFC Parser Version: 3.13.2
originating_system: Tekla Structures 2023 Service Pack 6, IFC Export Version: 4.0.0.0 Sep 28 2023
```

An error occurs while displaying the BCF viewpoint — the image is visible, but the camera point isn’t functioning.

<img width="2560" height="1494" alt="Image" src="https://github.com/user-attachments/assets/f2216a06-8614-4fc3-99b6-e8ce8a0e823f" />

```
Python: Traceback (most recent call last):
  File "C:\Users\j.sieses\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\bcf\operator.py", line 1269, in execute
    self.draw_lines(viewpoint, context)
  File "C:\Users\j.sieses\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\bcf\operator.py", line 1449, in draw_lines
    stroke = frame.strokes.new()
             ^^^^^^^^^^^^^^^^^
AttributeError: bpy_prop_collection: attribute "new" not found
```

[spekband.bcf.txt](https://github.com/user-attachments/files/23352630/spekband.bcf.txt)
Model opened: 
[Vebo Beton.ifc.txt](https://github.com/user-attachments/files/23352642/Vebo.Beton.ifc.txt)
[Model linked](https://acc.autodesk.com/docs/share/projects/32383bc1-521c-4a78-aebb-2e497a3d8559/files?shareId=4cac8cec-cf5d-494c-9b24-0934ff4ab69e)

### Debug and Error Output

```true

```

**Comment by BIMvoice** [comment]
To make this actionable: could you attach the BCF file (or a minimal one showing the bug) and the console error on 0.8.4+? BCF handling has moved since alpha251104, so confirming on a current daily narrows it to live code.

**Comment by PahlawanJoey** [comment]
> To make this actionable: could you attach the BCF file (or a minimal one showing the bug) and the console error on 0.8.4+? BCF handling has moved since alpha251104, so confirming on a current daily narrows it to live code.

@BIMvoice Latest daily build still gives me a bug, different message though.

```
Python: Traceback (most recent call last):
  File "C:\Users\j.sieses\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\bonsai\bim\module\bcf\operator.py", line 1266, in execute
    self.draw_lines(viewpoint, context)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\j.sieses\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\bonsai\bim\module\bcf\operator.py", line 1440, in draw_lines
    scene.grease_pencil = gp
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'grease_pencil'

```

Files:
[spekband.bcf.txt](https://github.com/user-attachments/files/23352630/spekband.bcf.txt)
Model opened:
[Vebo Beton.ifc.txt](https://github.com/user-attachments/files/23352642/Vebo.Beton.ifc.txt)
[Model linked](https://acc.autodesk.com/docs/share/projects/32383bc1-521c-4a78-aebb-2e497a3d8559/files?shareId=4cac8cec-cf5d-494c-9b24-0934ff4ab69e)

**Comment by BIMvoice** [comment]
@PahlawanJoey that traceback confirms it, and there is better news than expected: this was already fixed on 16 July, in **#8645**, which has been sitting open since.

**Your two reports are the same root cause.** The old Annotation Grease Pencil API has been dismantled progressively across Blender versions, so the same code broke in two different places:

```
Blender 4.5.8  (your Nov 2025 report)  operator.py:1446  frame.strokes.new()
                                        AttributeError: attribute "new" not found

Blender 5.x    (your report yesterday)  operator.py:1440  scene.grease_pencil = gp
                                        AttributeError: 'Scene' has no attribute 'grease_pencil'
```

Both were reproduced live against your actual `spekband.bcf` and `Vebo Beton.ifc`, and both stop happening with #8645 applied. Verified on Blender 4.5.8, 5.1.2 and 5.2.0, producing `layers=1 frames=1 strokes=3 points=6`, which matches the three `<Line>` elements in your BCF exactly.

The fix uses capability detection rather than a hardcoded version check, so it keeps working on Blender 4.2, which is the declared minimum.

One thing worth explaining, since it also explains your original symptom: the crash happens inside `draw_lines()`, which aborts before `setup_camera()` ever runs. That is why you saw the snapshot image load but the camera not align. One bug, two visible effects.

The PR shows a red check, but that run is 146 commits stale from 16 July and its failures are unrelated (rocksdb streaming, geometry tests, and a rate limited external API). Nothing in it touches the BCF module.

Nothing for you to update to, it is not in a build yet. Thanks for supplying the BCF and the model, they are what allowed this to be verified properly rather than assumed.

**Comment by BIMvoice** [comment]
Confirmed fixed, and you can ignore my request for a BCF file.

Your traceback points at line 1440 of the BCF module, `scene.grease_pencil = gp`. That is exactly the line #8645 removes, replacing it with code for the newer Grease Pencil API. Same line, same function.

#8645 is in BonsaiPR's current build, so updating should clear it.
