### ISSUE TITLE
BonsaiPR 11.06 not working

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#8167]
### Bug Description

Error after downloading latest PR version and installing it. When restarting Blender Bonsai won't load.

### Debug and Error Output

```true
os: Darwin
os_version: Darwin Kernel Version 25.5.0: Mon Apr 27 20:41:15 PDT 2026; root:xnu-12377.121.6~2/RELEASE_ARM64_T6041
python_version: 3.13.9
architecture: ('64bit', 'Mach-O')
machine: arm64
processor: arm
blender_version: 5.1.2
bonsai_version: 0.8.6-alpha260611
bonsai_commit_hash: 1652d25
bonsai_commit_date: 2026-06-11T23:36:10+02:00
bonsai_git_branch: build-0.8.6-alpha2606112335
last_actions: 
last_error: Traceback (most recent call last):
  File "/Users/petruc/Library/Application Support/Blender/5.1/extensions/raw_githubusercontent_com_001/bonsaiPR/__init__.py", line 278, in <module>
    import ifcopenshell.api
  File "/Users/petruc/Library/Application Support/Blender/5.1/extensions/.local/lib/python3.13/site-packages/ifcopenshell/__init__.py", line 98, in <module>
    from .ifcopenshell_wrapper import get_log, logger
ImportError: cannot import name 'logger' from 'ifcopenshell.ifcopenshell_wrapper' (/Users/petruc/Library/Application Support/Blender/5.1/extensions/.local/lib/python3.13/site-packages/ifcopenshell/ifcopenshell_wrapper.py)

binary_file_name: _ifcopenshell_wrapper.cpython-313-darwin.so
binary_python_version: 3.13
```

**Comment by theoryshaw** [comment]
I 'think' this might be from v0.8.0.  I could be wrong.

<details>
  <summary>AI assessment here....</summary>
  

That commit added this line to the SWIG interface [IfcParseWrapper.i:83](vscode-webview://0uht2pt7n3502ralol7juccjk8panv88deb28ujv5hqfbidgl0s6/src/ifcwrap/IfcParseWrapper.i#L83):


%rename("logger") Logger;
which exposes a new logger symbol in the compiled ifcopenshell_wrapper C++ extension. The matching Python source was updated too — [init.py:98](vscode-webview://0uht2pt7n3502ralol7juccjk8panv88deb28ujv5hqfbidgl0s6/src/ifcopenshell-python/ifcopenshell/__init__.py#L98):


from .ifcopenshell_wrapper import get_log, logger
So the Python source now requires a logger attribute that only exists in a freshly rebuilt ifcopenshell_wrapper.pyd.

Your Blender install has a mismatch:

✅ New Python source (__init__.py syncs from your repo, references logger)
❌ Old compiled ifcopenshell_wrapper.pyd (the precompiled binary in ...\.local\lib\python3.11\site-packages\ifcopenshell\) — predates the rename, so logger doesn't exist → ImportError.
How to fix
The compiled ifcopenshell_wrapper binary needs to be updated to match the Python source. Options, easiest first:

Update the precompiled wrapper — pull the latest ifcopenshell_wrapper.pyd (+ any updated .dlls) from a recent Bonsai/IfcOpenShell build that includes commit a7738eeb64, and drop it into ...AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\ifcopenshell\. This is what your dev-sync workflow normally copies.

Temporarily roll back the Python source to before the logger change, so it stops importing the symbol the old binary lacks — only viable if you don't need the new logger work.

Rebuild the wrapper from source if you have a local C++ build set up (slow).

</details>

**Comment by ZoomerHub** [comment]
I have the same problem ... meanwhile for daily build and PR build on all latest Blender versions (5.1, 5.2 Beta and 5.3 Alpha)

The Console Info is : 

os: Darwin
os_version: Darwin Kernel Version 25.5.0: Mon Apr 27 20:41:15 PDT 2026; root:xnu-12377.121.6~2/RELEASE_ARM64_T6041
python_version: 3.13.13
architecture: ('64bit', 'Mach-O')
machine: arm64
processor: arm
blender_version: 5.3.0 Alpha
bonsai_version: 0.8.6-alpha260611
bonsai_commit_hash: 0c993d3
bonsai_commit_date: 2026-06-11T09:28:27+02:00
bonsai_git_branch: v0.8.0
last_actions:
last_error: Traceback (most recent call last):
**File "/Users/user/Library/Application Support/Blender/5.3/extensions/raw_githubusercontent_com/bonsai/init.py", line 278, in
import ifcopenshell.api
File "/Users/user/Library/Application Support/Blender/5.3/extensions/.local/lib/python3.13/site-packages/ifcopenshell/init.py", line 98, in
from .ifcopenshell_wrapper import get_log, logger
ImportError: cannot import name 'logger' from 'ifcopenshell.ifcopenshell_wrapper' (/Users/user/Library/Application Support/Blender/5.3/extensions/.local/lib/python3.13/site-packages/ifcopenshell/ifcopenshell_wrapper.py)**

binary_file_name: _ifcopenshell_wrapper.cpython-313-darwin.so
binary_python_version: 3.13

**Comment by PahlawanJoey** [comment]
Same here, blender 5.1.2

`os: Windows
os_version: 10.0.26200
python_version: 3.13.9
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 198 Stepping 2, GenuineIntel
blender_version: 5.1.2
bonsai_version: 0.8.6-alpha260612
bonsai_commit_hash: 682bd0a
bonsai_commit_date: 2026-06-12T14:08:21-05:00
bonsai_git_branch: v0.8.0
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\raw_githubusercontent_com\bonsai\__init__.py", line 278, in <module>
    import ifcopenshell.api
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcopenshell\__init__.py", line 98, in <module>
    from .ifcopenshell_wrapper import get_log, logger
ImportError: cannot import name 'logger' from 'ifcopenshell.ifcopenshell_wrapper' (C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcopenshell\ifcopenshell_wrapper.py)

binary_file_name: _ifcopenshell_wrapper.cp313-win_amd64.pyd
binary_python_version: 3.13`

**Comment by Gorgious56** [comment]
Hello everyone who participated in the thread, could you elaborate on *how* you install and update Bonsai, as this will help pinpoint the issue. I would advise doing a clean install as this will ensure you have the latest files. Cheers

**Comment by aothms** [comment]
I also don't know how Bonsai PR works exactly, but I did introduce this logging behaviour that was backwards incompatible between older/newer builds, so I assume one way or another this should be fixed now with my latest commit, but I'm not fully aware if any GH actions or similar still need to be ran.

**Comment by PahlawanJoey** [comment]
@Gorgious56 

I have tried fully uninstalling and then restarting blender and installing again.

Just did it agian following this flow:

Open Blender -> Edit -> Preferences -> Get Extensions -> Bonsai Uninstall -> Close Blender
Open Blender  -> Edit -> Preferences -> Get Extensions -> Bonsai Install

Still getting:


```
os: Windows
os_version: 10.0.26200
python_version: 3.13.9
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 198 Stepping 2, GenuineIntel
blender_version: 5.1.2
bonsai_version: 0.8.6-alpha260614
bonsai_commit_hash: 3e7b739
bonsai_commit_date: 2026-06-14T20:27:49+02:00
bonsai_git_branch: v0.8.0
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\raw_githubusercontent_com\bonsai\__init__.py", line 278, in <module>
    import ifcopenshell.api
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcopenshell\__init__.py", line 98, in <module>
    from .ifcopenshell_wrapper import get_log, logger
ImportError: cannot import name 'logger' from 'ifcopenshell.ifcopenshell_wrapper' (C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcopenshell\ifcopenshell_wrapper.py)

binary_file_name: _ifcopenshell_wrapper.cp313-win_amd64.pyd
binary_python_version: 3.13
```

**Comment by PahlawanJoey** [comment]
I just deleted folder: C:\Users\pahlawan\AppData\Roaming\Blender Foundation\

Then I installed the latest build and now it's working again!

**Comment by ZoomerHub** [comment]
> Hello everyone who participated in the thread, could you elaborate on _how_ you install and update Bonsai, as this will help pinpoint the issue. I would advise doing a clean install as this will ensure you have the latest files. Cheers

When I initially install Bonsai I do it from Settings/Extensions by added custom paths for Bonsai daily and Bonsai PR.

Usually I only use Bonsai daily. I just deactivate it and switch to Bonsai PR only if daily does not load.

I update Bonsai always from Extensions, "refresh remote", one by one from Extensions Update list.
Then Bonsai usually wants a Blender restart which I do.

**Comment by ZoomerHub** [comment]
I tried today's daily update.

5.3
Bonsai daily (which does not load) was still activated.
After updating an error message, somthing like "IfcOpenShell has no attribute util ...."
This will deactivate Bonsai activation in AddOns
Restarted 5.3 -> activated Bonsai daily -> Bonsai works!

5.2
I deactivated Bonsai daily (which does not load) before updating.
tried to activate Bonsai daily, error message, "IfcOpenShell has no attribute util ...."
Restarted 5.2 -> activated Bonsai daily -> Bonsai works!

5.1
same.

**Comment by ZoomerHub** [comment]
> but I did introduce this logging behaviour that was backwards incompatible between older/newer builds, so I assume one way or another this should be fixed now with my latest commit

So it seems to work again (activating, loading)
Great !


I also see that opening the Demo Project, when loaded from Menu/File/Open Demo Project
also works fine now and also loads IfcTypes again.
(Last weeks It only load Types when opened from Bonsai Project Panel)

However, from time to time, after updating, I lose my Bonsai AddOn Settings (Extras)
(Today I lost them again)

**Comment by Tudjack** [comment]
I tried the latest daily build (alpha260618) on my Linux machine (Bazzite) and I see this error in the console on Blender startup. During installation I didn't get any errors.


WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/rdflib_sqlalchemy/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution
Traceback (most recent call last):
  File "/var/home/tudman/Blender/blender-5.1.0-linux-x64/5.1/scripts/modules/addon_utils.py", line 432, in enable
    mod = importlib.import_module(module_name)
  File "/var/home/tudman/Blender/blender-5.1.0-linux-x64/5.1/python/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/tudman/.config/blender/5.1/scripts/addons/bylor-extract-ifc-geometry/__init__.py", line 24, in <module>
    import ifc_geometry_extractor
  File "/home/tudman/.config/blender/5.1/scripts/addons/bylor-extract-ifc-geometry/ifc_geometry_extractor.py", line 7, in <module>
    import bonsai.bim
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/__init__.py", line 30, in <module>
    from . import handler, operator, parametric_lifecycle, prop, ui
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/operator.py", line 49, in <module>
    from bonsai.bim.ui import IFCFileSelector
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/ui.py", line 411, in <module>
    class BIM_ADDON_preferences(bpy.types.AddonPreferences):
    ...<490 lines>...
            layout.prop(self, "decorator_font_scale")
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/ui.py", line 412, in BIM_ADDON_preferences
    bl_idname = tool.Blender.get_blender_addon_package_name()
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/tool/blender.py", line 1885, in get_blender_addon_package_name
    return bonsai.REGISTERED_BBIM_PACKAGE
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'bonsai' has no attribute 'REGISTERED_BBIM_PACKAGE'
Traceback (most recent call last):
  File "/var/home/tudman/Blender/blender-5.1.0-linux-x64/5.1/scripts/modules/addon_utils.py", line 432, in enable
    mod = importlib.import_module(module_name)
  File "/var/home/tudman/Blender/blender-5.1.0-linux-x64/5.1/python/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/tudman/.config/blender/5.1/scripts/addons/bylo-Ifc-loader-bonsai/__init__.py", line 24, in <module>
    import bylor_ifc_loader
  File "/home/tudman/.config/blender/5.1/scripts/addons/bylo-Ifc-loader-bonsai/bylor_ifc_loader.py", line 2, in <module>
    import bonsai.bim
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/__init__.py", line 30, in <module>
    from . import handler, operator, parametric_lifecycle, prop, ui
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/operator.py", line 49, in <module>
    from bonsai.bim.ui import IFCFileSelector
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/ui.py", line 411, in <module>
    class BIM_ADDON_preferences(bpy.types.AddonPreferences):
    ...<490 lines>...
            layout.prop(self, "decorator_font_scale")
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/ui.py", line 412, in BIM_ADDON_preferences
    bl_idname = tool.Blender.get_blender_addon_package_name()
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/tool/blender.py", line 1885, in get_blender_addon_package_name
    return bonsai.REGISTERED_BBIM_PACKAGE
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'bonsai' has no attribute 'REGISTERED_BBIM_PACKAGE'
Traceback (most recent call last):
  File "/var/home/tudman/Blender/blender-5.1.0-linux-x64/5.1/scripts/modules/addon_utils.py", line 432, in enable
    mod = importlib.import_module(module_name)
  File "/var/home/tudman/Blender/blender-5.1.0-linux-x64/5.1/python/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/tudman/.config/blender/5.1/scripts/addons/bylor-pour-plugin/__init__.py", line 24, in <module>
    import bylor_pour
  File "/home/tudman/.config/blender/5.1/scripts/addons/bylor-pour-plugin/bylor_pour.py", line 3, in <module>
    import bonsai.bim
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/__init__.py", line 30, in <module>
    from . import handler, operator, parametric_lifecycle, prop, ui
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/operator.py", line 49, in <module>
    from bonsai.bim.ui import IFCFileSelector
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/ui.py", line 411, in <module>
    class BIM_ADDON_preferences(bpy.types.AddonPreferences):
    ...<490 lines>...
            layout.prop(self, "decorator_font_scale")
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/ui.py", line 412, in BIM_ADDON_preferences
    bl_idname = tool.Blender.get_blender_addon_package_name()
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/tool/blender.py", line 1885, in get_blender_addon_package_name
    return bonsai.REGISTERED_BBIM_PACKAGE
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'bonsai' has no attribute 'REGISTERED_BBIM_PACKAGE'

**Comment by Tudjack** [comment]
Also when trying to create a new project I get this error:


AttributeError: module 'bonsai' has no attribute 'REGISTERED_BBIM_PACKAGE'
Traceback (most recent call last):
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/module/project/operator.py", line 146, in execute
    self._execute(context)
    ~~~~~~~~~~~~~^^^^^^^^^
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/module/project/operator.py", line 162, in _execute
    core.create_project(
    ~~~~~~~~~~~~~~~~~~~^
        tool.Ifc, tool.Georeference, tool.Project, tool.Spatial, schema=props.export_schema, template=template
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/core/project.py", line 42, in create_project
    ifc.set(ifc.run("project.create_file", version=schema))
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/tool/ifc.py", line 68, in set
    cls.after_file_loaded()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/tool/ifc.py", line 77, in after_file_loaded
    bonsai.bim.schema.reload(IfcStore.file.schema_identifier)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'bonsai.bim' has no attribute 'schema'
04:41.055  bpy.rna          | ERROR Python script error in BIM_OT_create_project.execute
04:41.055  operator         | ERROR Python: Traceback (most recent call last):
                            |   File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/module/project/operator.py", line 146, in execute
                            |     self._execute(context)
                            |     ~~~~~~~~~~~~~^^^^^^^^^
                            |   File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/module/project/operator.py", line 162, in _execute
                            |     core.create_project(
                            |     ~~~~~~~~~~~~~~~~~~~^
                            |         tool.Ifc, tool.Georeference, tool.Project, tool.Spatial, schema=props.export_schema, template=template
                            |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            |     )
                            |     ^
                            |   File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/core/project.py", line 42, in create_project
                            |     ifc.set(ifc.run("project.create_file", version=schema))
                            |     ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            |   File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/tool/ifc.py", line 68, in set
                            |     cls.after_file_loaded()
                            |     ~~~~~~~~~~~~~~~~~~~~~^^
                            |   File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/tool/ifc.py", line 77, in after_file_loaded
                            |     bonsai.bim.schema.reload(IfcStore.file.schema_identifier)
                            |     ^^^^^^^^^^^^^^^^^
                            | AttributeError: module 'bonsai.bim' has no attribute 'schema'
Traceback (most recent call last):
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/module/project/ui.py", line 225, in draw
    self.draw_unsaved_project_ui(context)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/module/project/ui.py", line 356, in draw_unsaved_project_ui
    self.draw_editable_file_info(context)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/module/project/ui.py", line 338, in draw_editable_file_info
    value = getattr(ProjectData.data["header_info"], prop_name)
AttributeError: 'NoneType' object has no attribute 'mvd'
04:41.057  bpy.rna          | ERROR Python script error in BIM_PT_project.draw
Traceback (most recent call last):
  File "/home/tudman/.config/blender/5.1/extensions/.local/lib/python3.13/site-packages/bonsai/bim/module/search/ui.py", line 56, in draw
    bonsai.bim.helper.draw_filter(self.layout, props.filter_groups, SearchData, "search")
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'bonsai.bim' has no attribute 'helper'
04:41.058  bpy.rna          | ERROR Python script error in BIM_PT_search.draw

**Comment by BIMvoice** [comment]
For me it works now, the latest PR version.
