### ISSUE TITLE
No IfcOpenBot build for macOS python 3.11

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#4174]
Currently IfcOpenBot do not provide a build for macOS using python 3.11. Is there a reason ? Is it trying but failing ? Where is it possible to see what happens ?

**Comment by aothms** [comment]
Py 3.11 didn't compile on the OSX 10.16 build machine. so it has been deactivated on purpose, I forgot the details https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/nix/build-all.py#L286-L288 From the `git blame` I see that was added 2y ago, but maybe the 3.11.7 released on Dec 23 actually compiles fine on 10.16. Any ideas?

**Comment by CyrilWaechter** [comment]
No idea but it was a long time ago maybe it would worth to try to reactivate it and analyze the build log to see what happens if it still fails. I think python 3.11 is now default for Blender 4.0 which means that non arm macOS users will not be able to use blenderbim.

**Comment by Andrej730** [comment]
Python 3.10 is default for Blender 4.0 since they follow [VFX Platform](https://vfxplatform.com/), they'll switch to Python 3.11 only on March 19, 2024 with the Blender 4.1.

**Comment by Moult** [comment]
PyPI doesn't actually work, I uh... well... I didn't know how to exclude a single permutation of the matrix. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/Makefile#L60-L65

Would love to see if it compiles again now :)

**Comment by Andrej730** [comment]
@aothms can you please start python 3.11 build for macOS to see if there are still compilation errors? Blender will release new version next week and they'll move to python 3.11.

**Comment by aothms** [comment]
We have a nice rectangular matrix again :)

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/efd18ef7-8ee8-4add-9104-206a7d87b1cc)

**Comment by Andrej730** [comment]
Thank you!! 🥳🥳

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/47fd68a8-cd6c-4a5d-8fd0-0a7a1ad2720b)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/182a83b5-3360-4829-b72a-54790dc1c493)

**Comment by Moult** [comment]
FYI the evil hack for PyPI is now gone. https://github.com/IfcOpenShell/IfcOpenShell/commit/6555e566474ceb66e810ad2c4699848137179133
