### ISSUE TITLE
Compile error on lambda expression with gcc

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#891]
I don't understand. I successfully compiled ifcopenshell on April 12 2020 and now I get an error. Apparently code is 10 month old so I see no reason for this new error at this point.

Issue is apparently related to lambda expression in IfcGeomFunction.cpp :

https://github.com/IfcOpenShell/IfcOpenShell/blob/0237f12cebc5b1d324cb26b454e16414bc4d77e8/src/ifcgeom/IfcGeomFunctions.cpp#L4367

Error when compiling with gcc 10.1.0 :
```make
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/src/ifcgeom/IfcGeomFunctions.cpp: Dans la fonction lambda:
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/src/ifcgeom/IfcGeomFunctions.cpp:4367:36: erreur: « [0] = » utilisé dans une initialisation par désignation dans le style GNU pour la classe « std::array<int, 2> »
 4367 |     segment_set.insert({ { C, D } });
      |                                    ^
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/src/ifcgeom/IfcGeomFunctions.cpp: Dans la fonction membre « bool IfcGeom::KernelIfc4x1::convert_openings(const Ifc4x1::IfcProduct*, const ptr&, const IfcRepresentationShapeItems&, const gp_Trsf&, IfcGeom::IfcRepresentationShapeItems&) »:
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/src/ifcgeom/IfcGeomFunctions.cpp:755:38: attention: les qualificatifs de type sont ignorés sur le type résultant du transtypage [-Wignored-qualifiers]
  755 |    const unsigned int current_size = (const unsigned int) opening_shapes.size();
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/IfcGeom_ifc4.dir/build.make:109 : CMakeFiles/IfcGeom_ifc4.dir/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/src/ifcgeom/IfcGeomFunctions.cpp.o] Erreur 1
```

**Comment by aothms** [comment]
yes that's the downside of C++, sometimes a newer compiler decides the code you have written is invalid. I don't think there are a lot of people on gcc 10 yet. The default compiler on Ubuntu 20.04 is gcc 9.

Actually on further inspection this is a gcc bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95319

Is there any chance you can update gcc to 10.2.11.

Otherwise we probably need to fix this as bug reports will likely be pouring in for this soon.

`segment_set.insert({ { C, D } });` can probably be easily replaced by `				segment_set.insert(std::make_pair(C,D));`

**Comment by CyrilWaechter** [comment]
> yes that's the downside of C++, sometimes a newer compiler decides the code you have written is invalid. I don't think there are a lot of people on gcc 10 yet. The default compiler on Ubuntu 20.04 is gcc 9.

I assume it is part of rolling release drawback. You get fresh packages but also fresh bugs… 

> Is there any chance you can update gcc to 10.2.11.

I will try again when gcc 10.2.11 is released.

Side note :
I tried to compile with clang 10.0.0 of instead of gcc. Sadly I got another issue near the end.
```make
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:3594:17: error: use of undeclared identifier 'IteratorSettings'; did you mean 'IfcGeom::IteratorSettings'?
                        settings.get(IteratorSettings::LAYERSET_FIRST)
                                     ^~~~~~~~~~~~~~~~
                                     IfcGeom::IteratorSettings
```

**Comment by aothms** [comment]
That 2nd one was entirely on me, I thought I had already committed that. I also rewritten that lambda so to hopefully make gcc 10 happy as well. Can you check?

**Comment by CyrilWaechter** [comment]
Bad news is that compilation still fails. Good news is that clang and gcc now fail at same point : 
```make
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:3596:36: erreur: « GV_LAYERSET_FIRST » n'est pas un membre de « IfcGeom::Kernel »
 3596 |   kernel.setValue(IfcGeom::Kernel::GV_LAYERSET_FIRST,
      |                                    ^~~~~~~~~~~~~~~~~
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:3597:44: erreur: « LAYERSET_FIRST » n'est pas un membre de « IfcGeom::IteratorSettings »
 3597 |    settings.get(IfcGeom::IteratorSettings::LAYERSET_FIRST)
      |                                            ^~~~~~~~~~~~~~
```
There is a second batch of error later but I assume it is related to the first one : 
```make
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx: Dans la fonction « PyObject* _wrap_settings_offset_set(PyObject*, PyObject*) »:
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:4566:21: erreur: « class IfcGeom::IteratorSettings » n'a pas de membre nommé « offset »
 4566 |   if (arg1) (arg1)->offset = arg2;
      |                     ^~~~~~
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx: Dans la fonction « PyObject* _wrap_settings_offset_get(PyObject*, PyObject*) »:
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:4589:22: erreur: « class IfcGeom::IteratorSettings » n'a pas de membre nommé « offset »
 4589 |   result =  ((arg1)->offset);
      |                      ^~~~~~
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx: Dans la fonction « PyObject* _wrap_settings_rotation_set(PyObject*, PyObject*) »:
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:4626:21: erreur: « class IfcGeom::IteratorSettings » n'a pas de membre nommé « rotation »
 4626 |   if (arg1) (arg1)->rotation = arg2;
      |                     ^~~~~~~~
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx: Dans la fonction « PyObject* _wrap_settings_rotation_get(PyObject*, PyObject*) »:
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:4649:22: erreur: « class IfcGeom::IteratorSettings » n'a pas de membre nommé « rotation »
 4649 |   result =  ((arg1)->rotation);
      |                      ^~~~~~~~
```
Third batch : 
```make
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:23373:116: erreur: « LAYERSET_FIRST » n'est pas un membre de « IfcGeom::IteratorSettings »
23373 |   SWIG_Python_SetConstant(d, "settings_LAYERSET_FIRST",SWIG_From_int(static_cast< int >(IfcGeom::IteratorSettings::LAYERSET_FIRST)));
      |                                                                                                                    ^~~~~~~~~~~~~~
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:23374:113: erreur: « EDGE_ARROWS » n'est pas un membre de « IfcGeom::IteratorSettings »
23374 |   SWIG_Python_SetConstant(d, "settings_EDGE_ARROWS",SWIG_From_int(static_cast< int >(IfcGeom::IteratorSettings::EDGE_ARROWS)));
      |                                                                                                                 ^~~~~~~~~~~
```

**Comment by aothms** [comment]
Hm this doesn't look right. Somehow the code generated by SWIG does not appear to be inline with the headers from source. The code generated by SWIG is based on a newer version. Maybe try some make clean and git reset.

Somehow travis does not report status anymore, but it still runs the builds and it succeeds https://travis-ci.org/github/IfcOpenShell/IfcOpenShell/builds/698459495

**Comment by CyrilWaechter** [comment]
I tried to find what could differ between Travis and my system :
| Package       | Travis | Me            | Comment                                                                               |
|---------------|--------|---------------|---------------------------------------------------------------------------------------|
| Python        | 2.7    | 2.7.18  3.8.3 | I tried with both python2 and python3                                                 |
| swig          | 3.08   | 3.0.12 4.01   | I tried using swig 4 and swig 3                                                       |
| Boost         | 1.58   | 1.72          |                                                                                       |
| gcc           | 5.4.0  | 10.1.0        | Assuming it is not related as it also fails with clang                                |
| cmake         | 3.12   | 3.17.3        |                                                                                       |
| nlohmann-json | ?      | 3.7.3         | Wasn't active included as GLTF support was not on. Added but no relation as expected. |

Full [make_log.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/4786431/make_log.txt) just in case.
I cleaned build folder between try. I have git reset before tries.

**Comment by aothms** [comment]
> Full make_log.txt just in case.

Do you have one with `make clean` before?

This one did not rerun SWIG `Built target ifcopenshell_wrapper_swig_compilation`

**Comment by CyrilWaechter** [comment]
No, I reran it to keep only error but maybe it was wrong to do so for analysis. Here is the full log with make clean : [make_log.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/4797055/make_log.txt)

**Comment by aothms** [comment]
Thanks, I've seen this before with somebody else, but can't remember when and where.

The thing is, in:

```
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx: Dans la fonction « PyObject* _wrap_settings_offset_set(PyObject*, PyObject*) »:
/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:4566:21: erreur: « class IfcGeom::IteratorSettings » n'a pas de membre nommé « offset »
 4566 |   if (arg1) (arg1)->offset = arg2;
      |                     ^~~~~~
```

`_wrap_settings_offset_set()` is a function generated by SWIG based on the definition of `IteratorSettings` it's really strange than then during compilation it cannot find it anymore.

Roughly the same code is compiled for other files (IfcGeomFunctions.cpp for example) and there it doesn't complain. So it's something related to the IfcOpenShell headers found when compiling ifcwrap (perhaps it finds an installed older IfcOpenShell somewhere else and uses those headers, but it shouldn't because everything is relative paths).

Could you perhaps also upload `/home/cyril/git/ifcopenshell-git_v0.6.0/src/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:`?

**Comment by CyrilWaechter** [comment]
Ok. Here is the file you requested : [IfcPythonPYTHON_wrap.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4799507/IfcPythonPYTHON_wrap.zip)

**Comment by aothms** [comment]
Sorry for the late reply. Ok, that one file wasn't too helpful perhaps. Can you just share the entire directory of your clone? I assume there is nothing confidential (but by email is also fine).

**Comment by CyrilWaechter** [comment]
You can download full folder following [this link](https://courantlibre.biminsight.ch/index.php/s/Yq8NQpcaZmxRjbR).

**Comment by aothms** [comment]
Ugh, I really don't know. Can you help me try the following:

~~~
cd ./IfcOpenShell/build
# delete the python wrapper build output
rm -rf ifcwrap
make VERBOSE=1 _ifcopenshell_wrapper 2>&1 | grep /c++ | grep IfcPythonPYTHON_wrap.cxx
~~~

This will get you a command to compile the wrapper, mine was the following:

~~~
cd /home/ubuntu/IfcOpenShell/build/ifcwrap && /usr/bin/c++  -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_DATE_TIME_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -D_ifcopenshell_wrapper_EXPORTS -I/usr/include/opencascade -I/usr/include/python3.8 -I/home/ubuntu/IfcOpenShell/src/ifcwrap  -O3 -DNDEBUG -fPIC   -Wall -Wextra -Wno-maybe-uninitialized -fPIC -std=gnu++11 -o CMakeFiles/_ifcopenshell_wrapper.dir/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o -c /home/ubuntu/IfcOpenShell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx
~~~

Run this command, but add an `-E` after /usr/bin/c++ This will tell gcc to only run the preprocessor.

This will then get you a file (probably `CMakeFiles/_ifcopenshell_wrapper.dir/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o`) which is the C++ file with all `#includes` and macros resolved. That you should hopefully tell us why you get a conflicting IfcGeomIteratorSettings in the SWIG-generated source and includes. Would be great if you can attach that here, thanks in advance.

**Comment by CyrilWaechter** [comment]
I think I did it correctly following your instructions. Here is the file : [IfcPythonPYTHON_wrap.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4898068/IfcPythonPYTHON_wrap.zip)

**Comment by aothms** [comment]
This appears to be `IfcPythonPYTHON_wrap.cxx`, but we need `IfcPythonPYTHON_wrap.cxx`**`.o`** In the C++ command you ran the file path is after the `-o` switch.

**Comment by CyrilWaechter** [comment]
Oops, sorry. Then it should be this one : [IfcPythonPYTHON_wrap.cxx.o.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4901646/IfcPythonPYTHON_wrap.cxx.o.zip)

**Comment by aothms** [comment]
That's it thanks.

As suspected, it finds an installed ifcopenshell header, somehow based on the install path of opencascade

`# 24 "/usr/include/opencascade/../ifcgeom_schema_agnostic/../ifcgeom_schema_agnostic/../ifcgeom_schema_agnostic/../ifcgeom/IfcGeomIteratorSettings.h" 2`

I'll investigate more later.

**Comment by aothms** [comment]
For this build to succeed for now you can remove the includes in /usr/include/ifc* I think

**Comment by CyrilWaechter** [comment]
:tada: It works.
Now I just don't know if there is a way to solve this on my side for the packaging work. A previous version of ifcopenshell was installed that is why headers were found in `/usr/include/`. I didn't know that it could cause an issue as it wasn't before (if I remember well).
An [AUR](https://aur.archlinux.org/) package is just a recipe which create a package from source. As here it is based on git. It : 
1. compiles in a fakeroot
2. create package
3. install from package eventually upgrading from a previous version

In current process it will not work if a previous version is installed.

**Comment by CyrilWaechter** [comment]
The initial issue corresponding to title is fixed. 
I had not encountered again the issue concerning conflict with installed ifcopenshell version during compilation for a while so I'll close this. If necessary I will reopen a new issue with a more appropriate title.
