### ISSUE TITLE
BlenderBIM error on Blender 4.1

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4475]
Hey guys. Will BBIM work in Blender 4.1 soon? Or should we default to earlier version for a bit longer?

I get this error now. Tried both versions with py310 and py311.

`Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/petru/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/__init__.py", line 41, in <module>
    import blenderbim.bim
  File "/Users/petru/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "/Users/petru/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/handler.py", line 25, in <module>
    import blenderbim.tool as tool
  File "/Users/petru/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/tool/__init__.py", line 30, in <module>
    from blenderbim.tool.document import Document
  File "/Users/petru/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/tool/document.py", line 26, in <module>
    class Document(blenderbim.core.tool.Document):
                   ^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'blenderbim' has no attribute 'core' (most likely due to a circular import)

`

**Comment by Moult** [comment]
You need to download the py11 version. I'll do a release ASAP because otherwise everybody is going to face this problem.

**Comment by BIMvoice** [comment]
Can you please clarify? Are you saying that only the py3.11 BlenderBIM build will work with Blender 4.1? Or the release you plan to do should fix that and be possible to also use py.310 BlenderBIM build with it?

**Comment by Moult** [comment]
Only the python 3.11 builds will work with Blender 4.1. Currently the blenderbim.org website download the 3.10 build.

**Comment by BIMvoice** [comment]
Oh, I see. Thank you for the clarification. Then I have to upgrade Python on my machine.

**Comment by Moult** [comment]
You don't need to. Blender comes with its own Python which is separate from any other Python you install on your computer.

**Comment by BIMvoice** [comment]
Oh yeah, that's right. Thank you Dion, now it works as expected. Awesome stuff!
