### ISSUE TITLE
ExctractElements bug on latest daily build

### ISSUE THREAD

**Issue by PahlawanJoey** [IfcOpenShell/IfcOpenShell#8230]
### Bug Description

Latest daily build is giving me an error, previous versions worked before that (0.8.6-alpha260629).

If you need the model to debug let me know because it's huge.

```
os: Windows
os_version: 10.0.26200
python_version: 3.13.9
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 198 Stepping 2, GenuineIntel
blender_version: 5.1.2
bonsai_version: 0.8.6-alpha260701
bonsai_commit_hash: 340d4fb
bonsai_commit_date: 2026-07-01T11:03:35+02:00
bonsai_git_branch: v0.8.0
last_actions:
last_error: None
blend_file_path: Not saved
blend_file_dirty: N/A
ifc_file_path: No IFC loaded
ifc_is_dirty: N/A
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\bonsai\bim\module\patch\operator.py", line 87, in invoke
    return self.execute(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\bonsai\bim\module\patch\operator.py", line 131, in execute
    output = ifcpatch.execute(args)
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\__init__.py", line 125, in execute
    patcher.patch()
    ~~~~~~~~~~~~~^^
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\recipes\ExtractElements.py", line 93, in patch
    self.add_element(self.file.by_type("IfcProject")[0])
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\recipes\ExtractElements.py", line 100, in add_element
    new_element = self.append_asset(element)
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\recipes\ExtractElements.py", line 114, in append_asset
    for coop in ctx.HasCoordinateOperation:
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcopenshell\entity_instance.py", line 263, in __getattr__
    raise AttributeError(
        "entity instance of type '%s' has no attribute '%s'" % (self.wrapped_data.is_a(True), name)
    )
AttributeError: entity instance of type 'IFC2X3.IfcGeometricRepresentationContext' has no attribute 'HasCoordinateOperation'
11:22.734  bpy.rna          | ERROR Python script error in BIM_OT_execute_ifc_patch.invoke
11:22.734  operator         | ERROR Python: Traceback (most recent call last):
                            |   File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\bonsai\bim\module\patch\operator.py", line 87, in invoke
                            |     return self.execute(context)
                            |            ~~~~~~~~~~~~^^^^^^^^^
                            |   File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\bonsai\bim\module\patch\operator.py", line 131, in execute
                            |     output = ifcpatch.execute(args)
                            |   File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\__init__.py", line 125, in execute
                            |     patcher.patch()
                            |     ~~~~~~~~~~~~~^^
                            |   File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\recipes\ExtractElements.py", line 93, in patch
                            |     self.add_element(self.file.by_type("IfcProject")[0])
                            |     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            |   File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\recipes\ExtractElements.py", line 100, in add_element
                            |     new_element = self.append_asset(element)
                            |   File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\recipes\ExtractElements.py", line 114, in append_asset
                            |     for coop in ctx.HasCoordinateOperation:
                            |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
                            |   File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcopenshell\entity_instance.py", line 263, in __getattr__
                            |     raise AttributeError(
                            |         "entity instance of type '%s' has no attribute '%s'" % (self.wrapped_data.is_a(True), name)
                            |     )
                            | AttributeError: entity instance of type 'IFC2X3.IfcGeometricRepresentationContext' has no attribute 'HasCoordinateOperation'
Traceback (most recent call last):
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\bonsai\bim\module\patch\operator.py", line 87, in invoke
    return self.execute(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\bonsai\bim\module\patch\operator.py", line 131, in execute
    output = ifcpatch.execute(args)
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\__init__.py", line 125, in execute
    patcher.patch()
    ~~~~~~~~~~~~~^^
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\recipes\ExtractElements.py", line 93, in patch
    self.add_element(self.file.by_type("IfcProject")[0])
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\recipes\ExtractElements.py", line 100, in add_element
    new_element = self.append_asset(element)
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\recipes\ExtractElements.py", line 114, in append_asset
    for coop in ctx.HasCoordinateOperation:
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcopenshell\entity_instance.py", line 263, in __getattr__
    raise AttributeError(
        "entity instance of type '%s' has no attribute '%s'" % (self.wrapped_data.is_a(True), name)
    )
AttributeError: entity instance of type 'IFC2X3.IfcGeometricRepresentationContext' has no attribute 'HasCoordinateOperation'
13:34.297  bpy.rna          | ERROR Python script error in BIM_OT_execute_ifc_patch.invoke
13:34.297  operator         | ERROR Python: Traceback (most recent call last):
                            |   File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\bonsai\bim\module\patch\operator.py", line 87, in invoke
                            |     return self.execute(context)
                            |            ~~~~~~~~~~~~^^^^^^^^^
                            |   File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\bonsai\bim\module\patch\operator.py", line 131, in execute
                            |     output = ifcpatch.execute(args)
                            |   File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\__init__.py", line 125, in execute
                            |     patcher.patch()
                            |     ~~~~~~~~~~~~~^^
                            |   File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\recipes\ExtractElements.py", line 93, in patch
                            |     self.add_element(self.file.by_type("IfcProject")[0])
                            |     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            |   File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\recipes\ExtractElements.py", line 100, in add_element
                            |     new_element = self.append_asset(element)
                            |   File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\recipes\ExtractElements.py", line 114, in append_asset
                            |     for coop in ctx.HasCoordinateOperation:
                            |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
                            |   File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcopenshell\entity_instance.py", line 263, in __getattr__
                            |     raise AttributeError(
                            |         "entity instance of type '%s' has no attribute '%s'" % (self.wrapped_data.is_a(True), name)
                            |     )
                            | AttributeError: entity instance of type 'IFC2X3.IfcGeometricRepresentationContext' has no attribute 'HasCoordinateOperation'
```

Also should this say missing paths?:
<img width="473" height="991" alt="Image" src="https://github.com/user-attachments/assets/10b410aa-d327-4ef9-a07d-a8fe9c5def60" />

**Comment by PahlawanJoey** [comment]
```bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.bim.load_project_elements()
bpy.ops.bim.load_project(filepath="C:\\Users\\pahlawan\\Downloads\\Testmodel_3_kozijnen binnen.ifc", use_relative_path=False, should_start_fresh_session=True)
bpy.context.scene.BIMPatchProperties.ifc_patch_recipes = 'ExtractElements'
bpy.context.scene.BIMPatchProperties.should_load_from_memory = True
bpy.context.space_data.system_bookmarks_active = 3
bpy.context.space_data.params.filename = "Testmodel_3_kozijnen binnen_1.ifc"
bpy.ops.bim.select_ifc_patch_output(filepath="C:\\Users\\pahlawan\\Downloads\\Testmodel_3_kozijnen binnen_1.ifc")
bpy.ops.bim.patch_query_from_selected()
Python: Traceback (most recent call last):
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\bonsai\bim\module\patch\operator.py", line 87, in invoke
    return self.execute(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\bonsai\bim\module\patch\operator.py", line 131, in execute
    output = ifcpatch.execute(args)
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\__init__.py", line 125, in execute
    patcher.patch()
    ~~~~~~~~~~~~~^^
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\recipes\ExtractElements.py", line 93, in patch
    self.add_element(self.file.by_type("IfcProject")[0])
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\recipes\ExtractElements.py", line 100, in add_element
    new_element = self.append_asset(element)
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcpatch\recipes\ExtractElements.py", line 114, in append_asset
    for coop in ctx.HasCoordinateOperation:
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\.local\lib\python3.13\site-packages\ifcopenshell\entity_instance.py", line 263, in __getattr__
    raise AttributeError(
        "entity instance of type '%s' has no attribute '%s'" % (self.wrapped_data.is_a(True), name)
    )
AttributeError: entity instance of type 'IFC2X3.IfcGeometricRepresentationContext' has no attribute 'HasCoordinateOperation'
```

Here's a smaller model with the same bug: 

[Testmodel_3_kozijnen binnen.ifc.txt](https://github.com/user-attachments/files/29572983/Testmodel_3_kozijnen.binnen.ifc.txt)

**Comment by Gorgious56** [comment]
Hello, thanks for the report. I will look into it. Cheers

Seems caused by https://github.com/IfcOpenShell/IfcOpenShell/commit/e6dc582d8 - IFC2x3 does not have HasCoordinateOperation unless I'm mistaken. @aothms FWIW

**Comment by Gorgious56** [comment]
BTW yes the preset dropdown will display this message if you never added a preset for this recipe. It can be used to store and restore specific queries so you don't have to rewrite it every time. It's using the vanilla Blender preset system so it inherited its quirks, sorry. Cheers

**Comment by aothms** [comment]
Thanks @Gorgious56 @PahlawanJoey should be fixed
