### ISSUE TITLE
Build issues with OpenCasCade7.2 ?

### ISSUE THREAD

**Issue by yorikvanhavre** [IfcOpenShell/IfcOpenShell#372]
Hi Thomas & others,

It seems IfcOpenShell won't build with OpenCasCade7.2.0 ? (the official one from https://www.opencascade.com/content/latest-release ), using today's git version of IfcOpenShell. The same builds fine with OCC7.1 (I'm on debian buster).

I get this:

```
[ 83%] Building CXX object ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o
In file included from /home/yorik/Sources/build/ifcopenshell/ifcwrap/IfcPythonPYTHON_wrap.cxx:3221:0:
/home/yorik/Sources/IfcOpenShell/src/ifcwrap/../ifcgeom/IfcGeomTree.h: In member function ‘std::vector<_RealType> IfcGeom::impl::tree<T>::select(const T&, bool) const’:
/home/yorik/Sources/IfcOpenShell/src/ifcwrap/../ifcgeom/IfcGeomTree.h:114:47: error: cannot call member function ‘int IfcGeom::Kernel::count(const TopoDS_Shape&, TopAbs_ShapeEnum)’ without object
     if (IfcGeom::Kernel::count(A, TopAbs_SHELL) == 0) {
                                               ^
/home/yorik/Sources/IfcOpenShell/src/ifcwrap/../ifcgeom/IfcGeomTree.h:123:48: error: cannot call member function ‘int IfcGeom::Kernel::count(const TopoDS_Shape&, TopAbs_ShapeEnum)’ without object
      if (IfcGeom::Kernel::count(B, TopAbs_SHELL) == 0) {
                                                ^
/home/yorik/Sources/IfcOpenShell/src/ifcwrap/../ifcgeom/IfcGeomTree.h:130:60: error: cannot call member function ‘int IfcGeom::Kernel::count(const TopoDS_Shape&, TopAbs_ShapeEnum)’ without object
        if (IfcGeom::Kernel::count(cut.Shape(), TopAbs_SHELL) == 0) {
                                                            ^
/home/yorik/Sources/IfcOpenShell/src/ifcwrap/../ifcgeom/IfcGeomTree.h:137:63: error: cannot call member function ‘int IfcGeom::Kernel::count(const TopoDS_Shape&, TopAbs_ShapeEnum)’ without object
        if (IfcGeom::Kernel::count(common.Shape(), TopAbs_SHELL) > 0) {
                                                               ^
```

Plus other errors that seem caused by the ones above. Must be something that changed in OCC, but I'm not sure, the message seems to indicate something else (sorry, C++ noob) I'd be happy to help nailing that down, any hint as where to look?

Cheers
Yorik

**Comment by aothms** [comment]
Hi Yorik, uhm that seems odd, I don't think anything has changed there for a while, and I wouldn't see how this can be impacted by the OCC version. All the IfcOpenShell build scripts use 7.2. now.

> cannot call member function without object

Is an odd error, as the function is static `static int count(const TopoDS_Shape&, TopAbs_ShapeEnum);` https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeom.h#L208

Is your source directory completely clean? No local changes? conflicts?

Congratulations still on the recent freecad release btw! and I see the build instructions involving IfcopenShell have been updated https://www.freecadweb.org/wiki/Extra_python_modules#Linux_3

**Comment by yorikvanhavre** [comment]
> Edit: but you might want to recommend to clone from https://github.com/IfcOpenShell/IfcOpenShell.git instead of https://github.com/aothms/IfcOpenShell.git

Fixed, thanks!

About the build issue, yeah I thought it might not be really a bug... Thanks for looking anyway. I'll try redoing it from scratch. Let's keep this open until I find the solution, okay? Might be useful for others...

**Comment by yorikvanhavre** [comment]
Crazy.. Fresh recloned repo, fresh build dir, and still the same problem. And it builds ok with OCC 7.1... It doesn't make sense!
A bit further there is this other error too:
`/home/yorik/Sources/IfcOpenShell/src/ifcwrap/../ifcgeom/IfcGeomTree.h:270:77: error: ‘const class IfcGeom::Representation::BRep’ has no member named ‘as_compound’`
The investigation continues...

**Comment by aothms** [comment]
Interestingly #267 also mentions that error message bout `as_compound`, and that is also a FreeCAD user. I guess you are cloning from https://github.com/aothms/IfcOpenShell/ and not https://github.com/IfcOpenShell/IfcOpenShell/ I haven't been keeping them in sync for years :(

**Comment by aothms** [comment]
... but I just did

**Comment by yorikvanhavre** [comment]
I am pushing from the correct repo... The `cannot call member function without object` error is certainly wrong, probably the real cause is something else, and very probably some typical linux issue like a missing include, or maybe something that has moved in OCC (TopAbs_SHELL?) that windows finds automatically and linux not. Still investigating...

**Comment by yorikvanhavre** [comment]
Still same thing with occt7.3 (current master). Still don't have any idea of what's happening... :/

**Comment by aothms** [comment]
I don't know either. You're fork says `This branch is 1 commit ahead, 398 commits behind IfcOpenShell:master. `. Is there no way that can be related?

https://github.com/yorikvanhavre/IfcOpenShell

**Comment by yorikvanhavre** [comment]
I wasn't using that fork anymore, I'm pulling directly from the official IfcOpenShell one. I think github "resurrected" it when I did the pull request :) But this gave me another clue, I'll look at the gcc, swig, etc... versions that are used on travis and compare with mine here. Maybe some buggy combination is at work...

**Comment by aothms** [comment]
Hi Yorik, any updates on this?

**Comment by yorikvanhavre** [comment]
I'm afraid I kept procrastinating on this one :confounded: I've gone back to7.1... I'll try again to build against 7.3 this weekend.

**Comment by yorikvanhavre** [comment]
Sorry about the long time without feedback... Finally switched to 7.3 and the build issue is gone, everything goes fine again. Best bugs are those that fix themselves alone! ;)
