### ISSUE TITLE
[Bonsai] Blender crashes when trying to start a project from template -> installed Bonsai extension is the reason

### ISSUE THREAD

**Issue by dirkolbrich** [IfcOpenShell/IfcOpenShell#5674]
See opened (and closed) issue at the Blender project repo https://projects.blender.org/blender/blender/issues/129467

With the installed Bonsai extension, Blender crashes when I try to start a new Blender project from the splash screen other than the `General` option.

I could trace it back to the Bonsai extension after removing and reinstalling all extensions. Used Bonsai extension is the latest version v0.8.0 from the https://extensions.blender.org/ website.

**Comment by Andrej730** [comment]
@dirkolbrich 

Hi!
1) Does it crash with the latest build from releases too?
2) Does it crash if you start Blender with `blender --python-expr "import bpy; bpy.ops.wm.read_homefile(app_template='Video_Editing')" --background`?

**Comment by dirkolbrich** [comment]
Will test with with latest release of Bonsai.

Starting Blender 4.2.3 LTS via terminal with the Bonsai v0.8.0 version from the Blender extension store gives the following result:

```txt
~ /Applications/Blender.app/Contents/MacOS/Blender --python-expr "import bpy; bpy.ops.wm.read_homefile(app_template='Video_Editing')" --background

Blender 4.2.3 LTS (hash 0e22e4fcea03 built 2024-10-14 23:47:09)
Info: Registering operator class: 'OBJECT_OT_AlignOperator', bl_idname 'object.align' has been registered before, unregistering previous
register_class(...):
Info: Registering operator class: 'OBJECT_OT_AlignOperator', bl_idname 'object.align' has been registered before, unregistering previous
Error: KeyMapItem '' not found in KeyMap 'Object Mode'
Exception in module unregister(): '/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/blender_org/bonsai/__init__.py'
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.2/scripts/modules/addon_utils.py", line 537, in disable
    mod.unregister()
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/blender_org/bonsai/__init__.py", line 262, in unregister
    bonsai.bim.unregister()
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/__init__.py", line 285, in unregister
    mod.unregister()
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/geometry/__init__.py", line 154, in unregister
    km.keymap_items.remove(kmi)
RuntimeError: Error: KeyMapItem '' not found in KeyMap 'Object Mode'

Exception ignored in: <function ImagePreviewCollection.__del__ at 0x143dd23e0>
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.2/scripts/modules/bpy/utils/previews.py", line 63, in __del__
    raise ResourceWarning(
ResourceWarning: <ImagePreviewCollection id=0x15a824530[24], <super: <class 'ImagePreviewCollection'>, <ImagePreviewCollection object>>>: left open, remove with 'bpy.utils.previews.remove()'
Exception in module register(): /Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/blender_org/bonsai/__init__.py
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.2/scripts/modules/addon_utils.py", line 488, in enable
    mod.register()
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/blender_org/bonsai/__init__.py", line 254, in register
    bonsai.bim.register()
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/__init__.py", line 257, in register
    bpy.app.translations.register("bonsai", translations_dict)
ValueError: bpy.app.translations.register: translations message cache already contains some data for addon 'bonsai'

Blender quit
```

**Comment by dirkolbrich** [comment]
The python3.11 package [bonsai_py311-0.8.1-alpha241119-macos-arm64.zip](https://github.com/IfcOpenShell/IfcOpenShell/releases/download/bonsai-0.8.1-alpha2411191032/bonsai_py311-0.8.1-alpha241119-macos-arm64.zip) can not be installed, python version mismatch:

```
os: Darwin
os_version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
python_version: 3.11.7
architecture: ('64bit', '')
machine: arm64
processor: arm
blender_version: 4.2.3 LTS
bonsai_version: 0.8.1-alpha241119
bonsai_commit_hash: c7e7031
last_actions: 
last_error: Traceback (most recent call last):
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/ifcopenshell/__init__.py", line 84, in <module>
    from . import ifcopenshell_wrapper
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 13, in <module>
    from . import _ifcopenshell_wrapper
ImportError: cannot import name '_ifcopenshell_wrapper' from partially initialized module 'ifcopenshell' (most likely due to a circular import) (/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/ifcopenshell/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/user_default/bonsai/__init__.py", line 225, in <module>
    import ifcopenshell.api
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/ifcopenshell/__init__.py", line 86, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'darwin/64bit/python3.11'

binary_file_name: _ifcopenshell_wrapper.cpython-312-darwin.so
binary_python_version: 3.12
```


The installed python version of Blender should be correct, here is the first part of the blender system info:

```
========================================
= Blender 4.2.3 LTS System Information =
========================================


Blender:
========================================

version: 4.2.3 LTS, branch: blender-v4.2-release, commit date: 2024-10-14 15:20, hash: 0e22e4fcea03, type: Release
build date: 2024-10-14, 23:47:09
platform: 'macOS-15.1-arm64-arm-64bit'
binary path: '/Applications/Blender.app/Contents/MacOS/Blender'
build cflags:  -Wall -Werror=implicit-function-declaration -Werror=return-type -Wno-tautological-compare -Wno-unknown-pragmas -Wno-char-subscripts -Wstrict-prototypes -Wmissing-prototypes -Wunused-parameter -Wundef -Wundef-prefix -Werror=unguarded-availability-new  -mmacosx-version-min=11.2 -Xclang -fopenmp -I'/Users/blender/git/blender-v420/blender.git/lib/macos_arm64/openmp/include' -std=gnu11  -pipe -funsigned-char -fno-strict-aliasing -ffp-contract=off  
build cxxflags:  -Wall -Wc++20-designator -Wno-tautological-compare -Wno-unknown-pragmas -Wno-char-subscripts -Wno-overloaded-virtual -Wno-sign-compare -Wno-invalid-offsetof -Wno-suggest-override -Wundef -Wundef-prefix -Wunused-parameter -Wmismatched-tags -Werror=unguarded-availability-new  -mmacosx-version-min=11.2 -ftemplate-depth=1024 -Xclang -fopenmp -I'/Users/blender/git/blender-v420/blender.git/lib/macos_arm64/openmp/include'  -pipe -funsigned-char -fno-strict-aliasing -ffp-contract=off  
build linkflags: -fexceptions -framework CoreServices -framework Foundation -framework IOKit -framework AppKit -framework Cocoa -framework Carbon -framework AudioUnit -framework AudioToolbox -framework CoreAudio -framework Metal -framework QuartzCore -framework Accelerate -framework ForceFeedback -framework GameController -framework CoreHaptics -liconv -Wl,-unexported_symbols_list,'/Users/blender/git/blender-v420/blender.git/source/creator/symbols_apple.map' -Xlinker -no_warn_duplicate_libraries
build system: CMake

Python:
========================================

version: 3.11.7 (main, Jun 26 2024, 17:15:05) [Clang 15.0.0 (clang-1500.1.0.2.5)]
file system encoding: utf-8:surrogateescape
paths:
	'/Applications/Blender.app/Contents/Resources/4.2/scripts/startup'
	'/Applications/Blender.app/Contents/Resources/4.2/scripts/modules'
	'/Applications/Blender.app/Contents/Resources/4.2/python/lib/python311.zip'
	'/Applications/Blender.app/Contents/Resources/4.2/python/lib/python3.11'
	'/Applications/Blender.app/Contents/Resources/4.2/python/lib/python3.11/lib-dynload'
	'/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages'
	'/Applications/Blender.app/Contents/Resources/4.2/python/lib/python3.11/site-packages'
	'/Applications/Blender.app/Contents/Resources/4.2/scripts/freestyle/modules'
	'/Users/dirkolbrich/Library/Application Support/Blender/4.2/scripts/addons/modules'
	'/Applications/Blender.app/Contents/Resources/4.2/scripts/addons_core'
	'/Users/dirkolbrich/Library/Application Support/Blender/4.2/scripts/addons'

Python (External Binary):
========================================

binary path: '/Applications/Blender.app/Contents/Resources/4.2/python/bin/python3.11'
version: Python 3.11.7
```

I also tried it with the python3.12 [bonsai_py312-0.8.1-alpha241119-macos-arm64.zip](https://github.com/IfcOpenShell/IfcOpenShell/releases/download/bonsai-0.8.1-alpha2411191032/bonsai_py312-0.8.1-alpha241119-macos-arm64.zip) version, it also fails, see error message:

```
os: Darwin
os_version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
python_version: 3.11.7
architecture: ('64bit', '')
machine: arm64
processor: arm
blender_version: 4.2.3 LTS
bonsai_version: 0.8.1-alpha241119
bonsai_commit_hash: c7e7031
last_actions: 
last_error: Traceback (most recent call last):
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/ifcopenshell/__init__.py", line 84, in <module>
    from . import ifcopenshell_wrapper
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 13, in <module>
    from . import _ifcopenshell_wrapper
ImportError: cannot import name '_ifcopenshell_wrapper' from partially initialized module 'ifcopenshell' (most likely due to a circular import) (/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/ifcopenshell/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/user_default/bonsai/__init__.py", line 225, in <module>
    import ifcopenshell.api
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/ifcopenshell/__init__.py", line 86, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'darwin/64bit/python3.11'

binary_file_name: _ifcopenshell_wrapper.cpython-312-darwin.so
binary_python_version: 3.12
```

Could it be that both release versions of the package are build with python3.12?

**Comment by Andrej730** [comment]
@dirkolbrich 

Any chance you installed 3.12 first by accident?

Just downloaded https://github.com/IfcOpenShell/IfcOpenShell/releases/download/bonsai-0.8.1-alpha2411191032/bonsai_py311-0.8.1-alpha241119-macos-arm64.zip and it has python 3.11 when error traceback suggests you have binary for python 3.12 "_ifcopenshell_wrapper.cpython-312-darwin.so".
![image](https://github.com/user-attachments/assets/8239f517-d3e8-494d-a6c2-4a973b36d5fe)

**Comment by dirkolbrich** [comment]
Yeah seems so. I did several restarts during uninstall of Bonsai v0.8.0 and install of the latest release packages. Must have missed some steps.

Anyway, after installing `bonsai_py311-0.8.1-alpha241119-macos-arm64.zip` the error as described and the issue persist. Blender crashes. Here is the Apple error report:

[2024-11-19_problem report for blender.txt](https://github.com/user-attachments/files/17814965/2024-11-19_problem.report.for.blender.txt)

and the terminal result when starting from the command line:

```
~ /Applications/Blender.app/Contents/MacOS/Blender --python-expr "import bpy; bpy.ops.wm.read_homefile(app_template='Video_Editing')" --background

Blender 4.2.3 LTS (hash 0e22e4fcea03 built 2024-10-14 23:47:09)
Info: Registering operator class: 'OBJECT_OT_AlignOperator', bl_idname 'object.align' has been registered before, unregistering previous
register_class(...):
Info: Registering operator class: 'OBJECT_OT_AlignOperator', bl_idname 'object.align' has been registered before, unregistering previous
Info: Operator executed
Info: Operator executed
Error: KeyMapItem '' not found in KeyMap 'Object Mode'
Exception in module unregister(): '/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/user_default/bonsai/__init__.py'
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.2/scripts/modules/addon_utils.py", line 537, in disable
    mod.unregister()
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/user_default/bonsai/__init__.py", line 262, in unregister
    bonsai.bim.unregister()
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/__init__.py", line 285, in unregister
    mod.unregister()
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/geometry/__init__.py", line 162, in unregister
    km.keymap_items.remove(kmi)
RuntimeError: Error: KeyMapItem '' not found in KeyMap 'Object Mode'

Exception ignored in: <function ImagePreviewCollection.__del__ at 0x113df5ee0>
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.2/scripts/modules/bpy/utils/previews.py", line 63, in __del__
    raise ResourceWarning(
ResourceWarning: <ImagePreviewCollection id=0x14b5e8050[46], <super: <class 'ImagePreviewCollection'>, <ImagePreviewCollection object>>>: left open, remove with 'bpy.utils.previews.remove()'
Exception ignored in: <function ImagePreviewCollection.__del__ at 0x113df5ee0>
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.2/scripts/modules/bpy/utils/previews.py", line 63, in __del__
    raise ResourceWarning(
ResourceWarning: <ImagePreviewCollection id=0x14b5e80b0[46], <super: <class 'ImagePreviewCollection'>, <ImagePreviewCollection object>>>: left open, remove with 'bpy.utils.previews.remove()'
Exception in module register(): /Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/user_default/bonsai/__init__.py
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.2/scripts/modules/addon_utils.py", line 488, in enable
    mod.register()
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/user_default/bonsai/__init__.py", line 254, in register
    bonsai.bim.register()
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/__init__.py", line 257, in register
    bpy.app.translations.register("bonsai", translations_dict)
ValueError: bpy.app.translations.register: translations message cache already contains some data for addon 'bonsai'
Info: Operator executed

Blender quit
```

**Comment by Moult** [comment]
I can't recreate this on my Linux machine. I've tested launching Blender, going into the Splash Screen view Blender icon menu > Splash Screen, then clicking another preset that isn't General, and also doing `./blender --python-expr "import bpy; bpy.ops.wm.read_homefile(app_template='Video_Editing')" --background`.

I guess a few things to check:

 1. Can you try with Blender 4.3.2 from the Blender official website (i.e. not via another third party app store / homebrew / whatever)
 2. Can you try with the latest Bonsai unstable, not the stable version
 3. Can you ensure that Blender 4.3.2 is completely vanilla? No other add-ons or changes to settings.
 4. Can you confirm that you have no done any reset factory settings or otherwise, keeping things as vanilla as possible? Because on my machine at least once Bonsai is installed, there is no splash screen at all (unless you explicitly go to it via top menu).

 If things are still broken and we can't recreate it, can we organise a call / screenshare to live debug on your machine?

**Comment by dirkolbrich** [comment]
Hey Moult,

I usually use the most current Blender version via installer from the website, not via home-brew casks. Well, I gave it another try with a complete reinstall of the current versions. My system also changed a bit to a new M4 Max.

Starting a new Blender project from the provided templates works now, BUT the Blender splash screen is not displayed anymore on start-up. It can only be accessed via Blender icon -> Splash Screen. Weird.

- Blender installer  from the [Blender.org](http://blender.org/) website: `blender-4.3.2-macos-arm64.dmg`
- Latest unstable Bonsai installer from the Github release page: `bonsai_py311-0.8.1-alpha250201-macos-arm64.zip`
- Delete Blender from `/Applications/` folder
- completely deleting (well moving to a back-up location) of the folder `/Users/myUserName/Library/Application Support/Blender`
- Install Blender from the `.dmg` installer
- Open Blender -> first  splash screen appears for setting of keymap etc.
- After start default splash screen appears
- Selecting template „Video Editing“ -> Ok
- Selecting any other template -> OK
- Starting Blender with a template via the command line -> OK
```
/Applications/Blender.app/Contents/MacOS/Blender --python-expr "import bpy; bpy.ops.wm.read_homefile(app_template='Video_Editing')" --background
Blender 4.3.2 (hash 32f5fdce0a0a built 2024-12-17 02:14:25)

Blender quit
```

- Installing the Bonsai Add-on via Blender Preferences -> Add-Ons -> Install from disk
- Restart Blender -> the Blender splash screen does not appear any more (tried restarting several times)
- Opening new file from template via File -> New -> Video Editing -> OK
- Opening new file from template via Blender icon -> Splash Screen -> New File: Video Editing -> OK

So, the issue of a crashing Blender while starting a new project from a template is solved. New Issue of a disappearing splash screen.

**Comment by brunopostle** [comment]
I think that bonsai intentionally disables the blender splash screen, so this is expected

**Comment by Moult** [comment]
This is by design. If you disable "Setup workspace for BIM" in misc settings for the add-on you'll restore the default layout and splash screen.

**Comment by dirkolbrich** [comment]
> I think that bonsai intentionally disables the blender splash screen, so this is expected

> This is by design.

Ok, understood. But why? This is surprising, and in some way irritating. I think we once already had this discussion of an extension / add-on being a good citizen of the eco system and not changing default behaviour -> https://github.com/IfcOpenShell/IfcOpenShell/issues/4036

An installed add-on should not alter default behaviour of an app, if it is not relevant to the add-on.

**Comment by Moult** [comment]
Bonsai is not like other extensions. It doesn't "extend" the capabilities of Blender so much as "replace" the capabilities of Blender. In this scenario I think it's appropriate to completely revamp the UI. It adds over 1,000 new operators and 100 new UI panels and completely changes the file format and modeling paradigm.

**Comment by dirkolbrich** [comment]
I acknowledge your position. Let's just say we have a fundamentally different view on this.

[Blender for Artists](https://www.bforartists.de/) revamps the UI, but they also provide a separate installer. For the user it's clear they are not in Blender.

BonsaiBIM is "just" one of a plethora of extensions, which all add additional functionality. They all should live happily next to each other and don't interfere in each others business. For me as a user it is highly irritating when some known functionality is altered without any apparent reason or connection to an extension. Does BonsaiBIM needs to shut down the splash screen to run?
