### ISSUE TITLE
PythonOCC >=7.8.0 ifcopenshell.geom.serialise doesn't work because BRepTools_ShapeSet.WriteToString signature changed

### ISSUE THREAD

**Issue by arunkvijay** [IfcOpenShell/IfcOpenShell#6099]
I'm trying to create `IfcSpace` from walls & slabs and have successfully created the TopoDS_Compound shape. However, while trying to serialise this shape and create a representation, I get the following error message
```
(Pdb) space_shape
<class 'TopoDS_Compound'>
(Pdb) ifcopenshell.geom.serialise(f.schema, space_shape)
*** TypeError: BRepTools_ShapeSet.WriteToString() missing 1 required positional argument: 'shape'

```
I'm currently using ifcopenshell version 0.8.0 and pythonocc version 7.8.1.1.

I'm wondering if this is due to any of the recent updates as I could do serialisation as above with ifcopenshell version 0.7.0 and pythonocc 7.7.0.

How do I serialise this shape correctly now

EDIT:
I've also tried serialising with TopoDS_Solid extracted from TopoDS_Compound, but even that has the same error output

**Comment by arunkvijay** [comment]
Just reconfirming that the serialization is not working with ifcopenshell version 0.8.0 and latest pythonocc version 7.8.1.1. 
Is this a known bug? Any guidance on resolving this would be very helpful. Thanks in advance.

**Comment by Moult** [comment]
Is this what you were after?

```python
    settings = ifcopenshell.geom.settings()
    # A string representation of the OCC representation
    settings.set("iterator-output", ifcopenshell.ifcopenshell_wrapper.NATIVE)
    # A string representation of the OCC representation
    settings.set("iterator-output", ifcopenshell.ifcopenshell_wrapper.SERIALIZED)
    shape = ifcopenshell.geom.create_shape(settings, element)
    print(shape.geometry.brep_data)

    # CASCADE Topology V1, (c) Matra-Datavision
    # Locations 0
    # Curve2ds 0
    # Curves 12
    # 1 4.6750000000000034 -8.0749999999999904 2.657 -2.0455514041918775e-15 -1 0
    # 1 4.6750000000000034 -8.0749999999999904 2.657 1 -3.435893306383461e-15 0
    # 1 6.2260000000000044 -8.0749999999999957 2.657 -2.0455514041918724e-15 -1 0
    # 1 6.226 -10.246000000000031 2.657 -1 6.8717866127669219e-15 0
    # ...
```

**Comment by arunkvijay** [comment]
Hi @Moult , 
not this as this is for generating shape from an Ifc Element (right?)
I'm creating a TopoDS_Solid in pythonocc that needs to be added as a representation in Ifc. 
`ifcopenshell.geom.serialise(f.schema, space_shape)` used to work earlier ( with  ifcopenshell version 0.7.0 and pythonocc 7.7.0). 
This causes an error now `*** TypeError: BRepTools_ShapeSet.WriteToString() missing 1 required positional argument: 'shape'`

Hope this helps. Happy to share more info too

**Comment by Moult** [comment]
Sorry, completely misread. Have you tried adding the third bool arg? E.g: `ifcopenshell.geom.serialise(f.schema, shape, True)`? I think (not sure) that this is to do with whether or not the schema contains advanced breps.

**Comment by arunkvijay** [comment]
yes, did try `ifcopenshell.geom.serialise(f.schema, shape, True)` as well. but same error. 
I'm guessing that this is a bug as earlier version (ifcopenshell + pythonocc) used to work well.

**Comment by aothms** [comment]
It looks like WriteToString indeed became a static method at some point?

https://github.com/tpaviot/pythonocc-core/blob/7a6fec732fdfbd4bda5414439b2dd039b85ddadc/src/SWIG_files/wrapper/BRepTools.i#L2555

Maybe you could experiment a bit what works on your end. (Maybe just the static `OCC.Core.BRepTools.WriteToString`). I don't have that, but I'm on a much older version.

```
>>> OCC.Core.BRepTools.WriteToString
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'OCC.Core.BRepTools' has no attribute 'WriteToString'
>>> print(OCC.VERSION)
7.5.1
```

https://github.com/IfcOpenShell/IfcOpenShell/blob/11c6b55f7c1e57dec568d57e0928ed2cc235ad6e/src/ifcopenshell-python/ifcopenshell/geom/occ_utils.py#L229

**Comment by arunkvijay** [comment]
Thanks @aothms , will check this out.

**Comment by DaivaMarcinkeviciute** [comment]
I am having the same issue.
I am using:
- ifcopenshell version 0.8.1 
- pythonocc version 7.8.1.1 (same as @arunkvijay )

It worked fine when i had:
- ifcopenshell version 0.7.0
- pythonocc version 7.7.0

**Comment by DaivaMarcinkeviciute** [comment]
Is there another way to write an OCC geometry into an IFC file? 
I tried also ifcopenshell.geom.main.tesselate, but it faces the same issue.

**Comment by arunkvijay** [comment]
@DaivaMarcinkeviciute The serialization works well on pythonocc-core 7.7.0, and is easy to setup with conda env. 
I'm finding it difficult trying to build from source on Debian 12 as OCCT build is failing

**Comment by DaivaMarcinkeviciute** [comment]
> [@DaivaMarcinkeviciute](https://github.com/DaivaMarcinkeviciute) The serialization works well on pythonocc-core 7.7.0, and is easy to setup with conda env. I'm finding it difficult trying to build from source on Debian 12 as OCCT build is failing

I have also installed both PythonOCC and OCCT via anaconda. I have not tried building it locally.

**Comment by Moult** [comment]
Bump ping @yorikvanhavre did you face this same issue in FreeCAD?

**Comment by yorikvanhavre** [comment]
> Bump ping [@yorikvanhavre](https://github.com/yorikvanhavre) did you face this same issue in FreeCAD?

I did, in fact 😅 and forgot to look further into it...

**Comment by arunkvijay** [comment]
I've done a few experiments and these are my observations:

- serialisation with `ifcopenshell.geom.serialise` works for the combination of pythonocc-core build from source for v7.5.1 and ifcopenshell v0.7.10. Later version of ifcopenshell fails with Segmentation Fault error
- `ifcopenshell.geom.tesselate` also fails as I guess the .brep version output by pythonocc-core is V3 and is not recognised by ifcopenshell

**Comment by DaivaMarcinkeviciute** [comment]
After getting some additional tips from the IfcOpenShell developers, i changed the following function: 
https://github.com/IfcOpenShell/IfcOpenShell/blob/11c6b55f7c1e57dec568d57e0928ed2cc235ad6e/src/ifcopenshell-python/ifcopenshell/geom/occ_utils.py#L220-L231

The new definition is:

    def serialize_shape(shape):
        shapes = BRepTools.BRepTools_ShapeSet()

        # @todo provide method to get ifcopenshell's built-in occt version to
        # see whether this is necessary
        shapes.SetFormatNb(2)

        shapes.Add(shape)
	    return shapes.Write()


After this change "ifcopenshell.geom.main.tesselate()" seams to work fine.

Thanks for the tips @Moult  and Thomas!

**Comment by aothms** [comment]
Ok, interesting, the WriteToString() wasn't added so long ago as a compatibility mechanism.

Maybe the most failsafe is to use some introspection so that we only call WriteToString() when it accepts the right number of arguments (1, i.e `self`) and not the additional argument in the error message from OP:

> error "BRepTools_ShapeSet.WriteToString() missing 1 required positional argument: 'shape'"

     if hasattr(shapes, "WriteToString") and len(inspect.signature(shapes.WriteToString).parameters) == 1: 
         return shapes.WriteToString() 
     else: 
         return shapes.Write()

Anyway, feel free to cook up something that appears backwards compatible enough as a PR. Would be appreciated.
