### PR TITLE
Fix #7878: Fix snapping crash with non-mesh objects

### LINKED ISSUE #7878: Error when placing a beam.
When placing a beam, i get the following error. 

You have to hover over the origin for some reason. 

https://github.com/user-attachments/assets/49f84685-1bbd-49da-8d04-1c054f57e111

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 527, in execute_ifc_operator
    result = getattr(operator, "_modal")(context, event)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\profile.py", line 1184, in _modal
    self.handle_mouse_move(context, event, should_round=True)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\polyline.py", line 411, in handle_mouse_move
    detected_snaps = tool.Snap.detect_snapping_points(context, event, self.objs_2d_bbox, self.tool_state)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\tool\snap.py", line 391, in detect_snapping_points
    objs_to_raycast = tool.Raycast.filter_objects_to_raycast(context, event, objs_2d_bbox)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\tool\raycast.py", line 733, in filter_objects_to_raycast
    snap_obj = cls.create_snap_obj(obj)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\tool\raycast.py", line 900, in create_snap_obj
    snap_obj = SnapObj(obj)
               ^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\tool\raycast.py", line 935, in __init__
    self.root.edges = [e.index for e in obj.data.edges]
                                        ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'edges'

```

### PR DESCRIPTION
**Pull request by theoryshaw**
Two bugs introduced in 31b571322:
- SnapObj assumed obj.data is always a Mesh; non-mesh objects (empties, lights, etc.) have obj.data = None, causing an AttributeError on obj.data.edges.
- view3d_utils was used but never imported.

Generated with the assistance of an AI coding tool.

### CODE REVIEW

**Comment by theoryshaw** [comment]
@brunoperdigao Can you review and pull, if this seems okay?

**Comment by brunoperdigao** [comment]
@theoryshaw thanks for the fix, seems fine.
