### ISSUE TITLE
compile error on debian jessie

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#184]
I get a compile error on latest IFCOS  commit  704 https://github.com/IfcOpenShell/IfcOpenShell/commit/332a9a5 I haven't tried to compile for a few weeks. I'm on Debian Jessie. Does someone has an idea?

my output:

~~~
$ make
[  3%] Building CXX object CMakeFiles/IfcParse.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcparse/IfcWrite.cpp.o
[  6%] Building CXX object CMakeFiles/IfcParse.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcparse/IfcLateBoundEntity.cpp.o
[  9%] Building CXX object CMakeFiles/IfcParse.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcparse/IfcUtil.cpp.o
[ 12%] Building CXX object CMakeFiles/IfcParse.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcparse/IfcCharacterDecoder.cpp.o
[ 15%] Building CXX object CMakeFiles/IfcParse.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcparse/IfcSpfHeader.cpp.o
[ 18%] Building CXX object CMakeFiles/IfcParse.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcparse/IfcParse.cpp.o
[ 21%] Building CXX object CMakeFiles/IfcParse.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcparse/IfcSIPrefix.cpp.o
[ 24%] Building CXX object CMakeFiles/IfcParse.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcparse/IfcLogger.cpp.o
[ 27%] Building CXX object CMakeFiles/IfcParse.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcparse/IfcGlobalId.cpp.o
[ 30%] Building CXX object CMakeFiles/IfcParse.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcparse/Ifc2x3-latebound.cpp.o
[ 33%] Building CXX object CMakeFiles/IfcParse.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcparse/Ifc2x3.cpp.o
[ 36%] Building CXX object CMakeFiles/IfcParse.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcparse/IfcHierarchyHelper.cpp.o
Linking CXX static library libIfcParse.a
[ 36%] Built target IfcParse
[ 39%] Building CXX object CMakeFiles/IfcGeom.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcgeom/IfcGeomRenderStyles.cpp.o
[ 42%] Building CXX object CMakeFiles/IfcGeom.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcgeom/IfcGeomShapes.cpp.o
[ 45%] Building CXX object CMakeFiles/IfcGeom.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcgeom/IfcGeomHelpers.cpp.o
[ 48%] Building CXX object CMakeFiles/IfcGeom.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcgeom/IfcRegister.cpp.o
[ 51%] Building CXX object CMakeFiles/IfcGeom.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcgeom/IfcGeomFunctions.cpp.o
[ 54%] Building CXX object CMakeFiles/IfcGeom.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcgeom/IfcGeomWires.cpp.o
[ 57%] Building CXX object CMakeFiles/IfcGeom.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcgeom/IfcGeomFaces.cpp.o
[ 60%] Building CXX object CMakeFiles/IfcGeom.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcgeom/IfcGeomRepresentation.cpp.o
[ 63%] Building CXX object CMakeFiles/IfcGeom.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcgeom/IfcGeomMaterial.cpp.o
[ 66%] Building CXX object CMakeFiles/IfcGeom.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcgeom/IfcGeomCurves.cpp.o
[ 69%] Building CXX object CMakeFiles/IfcGeom.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcgeom/IfcGeomSerialisation.cpp.o
Linking CXX static library libIfcGeom.a
[ 69%] Built target IfcGeom
[ 72%] Building CXX object CMakeFiles/IfcConvert.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcconvert/util.cpp.o
[ 75%] Building CXX object CMakeFiles/IfcConvert.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcconvert/ColladaSerializer.cpp.o
[ 78%] Building CXX object CMakeFiles/IfcConvert.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcconvert/IfcConvert.cpp.o
[ 81%] Building CXX object CMakeFiles/IfcConvert.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcconvert/WavefrontObjSerializer.cpp.o
[ 84%] Building CXX object CMakeFiles/IfcConvert.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcconvert/OpenCascadeBasedSerializer.cpp.o
[ 87%] Building CXX object CMakeFiles/IfcConvert.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcconvert/XmlSerializer.cpp.o
[ 90%] Building CXX object CMakeFiles/IfcConvert.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcconvert/SvgSerializer.cpp.o
Linking CXX executable IfcConvert
[ 90%] Built target IfcConvert
[ 93%] Building CXX object CMakeFiles/IfcGeomServer.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcgeomserver/IfcGeomServer.cpp.o
Linking CXX executable IfcGeomServer
[ 93%] Built target IfcGeomServer
[ 96%] Swig source
[ 96%] Swig source
[100%] Building CXX object ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/build/ifcwrap/IfcPythonPYTHON_wrap.cxx: In function ‘PyObject* _wrap_iterator_single_precision_get_native(PyObject*, PyObject*)’:
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/build/ifcwrap/IfcPythonPYTHON_wrap.cxx:6420:57: error: ‘class IfcGeom::Iterator<float>’ has no member named ‘get_native’
       result = (IfcGeom::BRepElement< float > *)(arg1)->get_native();
                                                         ^
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/build/ifcwrap/IfcPythonPYTHON_wrap.cxx: In function ‘PyObject* _wrap_iterator_double_precision_get_native(PyObject*, PyObject*)’:
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/build/ifcwrap/IfcPythonPYTHON_wrap.cxx:7477:58: error: ‘class IfcGeom::Iterator<double>’ has no member named ‘get_native’
       result = (IfcGeom::BRepElement< double > *)(arg1)->get_native();
                                                          ^
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/build/ifcwrap/IfcPythonPYTHON_wrap.cxx: In function ‘void init_ifcopenshell_wrapper()’:
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/build/ifcwrap/IfcPythonPYTHON_wrap.cxx:18011:83: error: ‘TRAVERSE’ is not a member of ‘IfcGeom::IteratorSettings’
   SWIG_Python_SetConstant(d, "settings_TRAVERSE",SWIG_From_int(static_cast< int >(IfcGeom::IteratorSettings::TRAVERSE)));
                                                                                   ^
ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/build.make:62: recipe for target 'ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o' failed
make[2]: *** [ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:218: recipe for target 'ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/all' failed
make[1]: *** [ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
$
~~~

**Comment by Stinkfist0** [comment]
Try rerunning cmake or recompiling the _ifcopenshell_wrapper project, that should help.

**Comment by berndhahnebach** [comment]
it is what I did before I made the post. Deleted the whole build directory and rerun cmake and make. I did it again. Just pullt the repo again to a fresh directory, new fresh build directory and fresh cmake and make run, same error

bernd

**Comment by Stinkfist0** [comment]
OK, for me the generated code for ifcopenshell_wrapper is outdated occasionally, but rebuilding it explicitly helps.

**Comment by berndhahnebach** [comment]
I played a bit with git bisect:
last compiling commit for me is https://github.com/IfcOpenShell/IfcOpenShell/commit/739bbcc
first not compiling commit for me is https://github.com/IfcOpenShell/IfcOpenShell/commit/714a365

the error on commit  714a365 is

~~~
[ 87%] Building CXX object ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/build/ifcwrap/IfcPythonPYTHON_wrap.cxx: In function ‘void init_ifcopenshell_wrapper()’:
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/build/ifcwrap/IfcPythonPYTHON_wrap.cxx:18011:83: error: ‘TRAVERSE’ is not a member of ‘IfcGeom::IteratorSettings’
   SWIG_Python_SetConstant(d, "settings_TRAVERSE",SWIG_From_int(static_cast< int >(IfcGeom::IteratorSettings::TRAVERSE)));
                                                                                   ^
[ 90%] Building CXX object CMakeFiles/IfcConvert.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcconvert/OpenCascadeBasedSerializer.cpp.o
ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/build.make:62: recipe for target 'ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o' failed
make[2]: *** [ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:218: recipe for target 'ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/all' failed
make[1]: *** [ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/all] Error 2
make[1]: *** Warte auf noch nicht beendete Prozesse...
[ 93%] Building CXX object CMakeFiles/IfcConvert.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcconvert/XmlSerializer.cpp.o
Linking CXX executable IfcGeomServer
[ 93%] Built target IfcGeomServer
[ 96%] Building CXX object CMakeFiles/IfcConvert.dir/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-official/ifcos/src/ifcconvert/SvgSerializer.cpp.o
Linking CXX executable IfcConvert
[100%] Built target IfcConvert
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
~~~

**Comment by aothms** [comment]
Well, I tend to agree with @Stinkfist0, somehow your SWIG-generated cxx file does get updated, but it seems it includes older header files? The error `error: ‘TRAVERSE’ is not a member of ‘IfcGeom::IteratorSettings’` complains about exactly the thing that is introduced in that particular commit that fails. Are you sure your working tree is clean, i.e. nothing in `git status`?

Otherwise, I'd say let's take a look at the preprocessed code to verify what is really going on. So, run make as `make VERBOSE=1` and run the command for compiling `IfcPythonPYTHON_wrap.cxx` but instead add a `-E` to `g++` or alternatively, run `cpp` instead of `g++` to get the preprocessed code.

**Comment by berndhahnebach** [comment]
as I wrote clean build. Just pulled all source from github again in a new directory. new build folder ...

~~~

$ make VERBOSE=1
/usr/bin/cmake -H/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/cmake -B/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/CMakeFiles /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
make -f CMakeFiles/IfcParse.dir/build.make CMakeFiles/IfcParse.dir/depend
make[2]: Entering directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
cd /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/cmake /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/cmake /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/CMakeFiles/IfcParse.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
make -f CMakeFiles/IfcParse.dir/build.make CMakeFiles/IfcParse.dir/build
make[2]: Entering directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
make[2]: Nothing to be done for 'CMakeFiles/IfcParse.dir/build'.
make[2]: Leaving directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
/usr/bin/cmake -E cmake_progress_report /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/CMakeFiles  20 21 22 23 24 25 26 27 28 29 30 31
[ 36%] Built target IfcParse
make -f CMakeFiles/IfcGeom.dir/build.make CMakeFiles/IfcGeom.dir/depend
make[2]: Entering directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
cd /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/cmake /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/cmake /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/CMakeFiles/IfcGeom.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
make -f CMakeFiles/IfcGeom.dir/build.make CMakeFiles/IfcGeom.dir/build
make[2]: Entering directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
make[2]: Nothing to be done for 'CMakeFiles/IfcGeom.dir/build'.
make[2]: Leaving directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
/usr/bin/cmake -E cmake_progress_report /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/CMakeFiles  8 9 10 11 12 13 14 15 16 17 18
[ 69%] Built target IfcGeom
make -f CMakeFiles/IfcConvert.dir/build.make CMakeFiles/IfcConvert.dir/depend
make[2]: Entering directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
cd /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/cmake /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/cmake /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/CMakeFiles/IfcConvert.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
make -f CMakeFiles/IfcConvert.dir/build.make CMakeFiles/IfcConvert.dir/build
make[2]: Entering directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
make[2]: Nothing to be done for 'CMakeFiles/IfcConvert.dir/build'.
make[2]: Leaving directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
/usr/bin/cmake -E cmake_progress_report /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/CMakeFiles  1 2 3 4 5 6 7
[ 90%] Built target IfcConvert
make -f CMakeFiles/IfcGeomServer.dir/build.make CMakeFiles/IfcGeomServer.dir/depend
make[2]: Entering directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
cd /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/cmake /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/cmake /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/CMakeFiles/IfcGeomServer.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
make -f CMakeFiles/IfcGeomServer.dir/build.make CMakeFiles/IfcGeomServer.dir/build
make[2]: Entering directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
make[2]: Nothing to be done for 'CMakeFiles/IfcGeomServer.dir/build'.
make[2]: Leaving directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
/usr/bin/cmake -E cmake_progress_report /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/CMakeFiles  19
[ 93%] Built target IfcGeomServer
make -f ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/build.make ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/depend
make[2]: Entering directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
cd /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/cmake /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/DependInfo.cmake --color=
Deleting primary custom command output "/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/IfcPythonPYTHON_wrap.cxx" because another output "/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/IfcPython.py" does not exist.
make[2]: Leaving directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
make -f ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/build.make ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/build
make[2]: Entering directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
/usr/bin/cmake -E cmake_progress_report /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/CMakeFiles 32
[ 96%] Swig source
cd /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap && /usr/bin/cmake -E make_directory /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap
cd /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap && /usr/bin/swig2.0 -python -outdir /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap -c++ -I/usr/local/include/opencascade -I/usr/include -I/usr/include/python2.7 -I/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap -o /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/IfcPythonPYTHON_wrap.cxx /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap/IfcPython.i
/usr/bin/cmake -E cmake_progress_report /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/CMakeFiles 33
[100%] Building CXX object ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o
cd /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap && /usr/bin/c++   -DHAVE_ICU -DUSE_IFC2x3 -D_ifcopenshell_wrapper_EXPORTS -O3 -DNDEBUG -fPIC -I/usr/local/include/opencascade -I/usr/include/python2.7 -I/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap    -Wall -Wextra -fPIC -std=c++11 -o CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o -c /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/IfcPythonPYTHON_wrap.cxx
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/IfcPythonPYTHON_wrap.cxx: In function ‘PyObject* _wrap_iterator_single_precision_get_native(PyObject*, PyObject*)’:
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/IfcPythonPYTHON_wrap.cxx:6420:57: error: ‘class IfcGeom::Iterator<float>’ has no member named ‘get_native’
       result = (IfcGeom::BRepElement< float > *)(arg1)->get_native();
                                                         ^
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/IfcPythonPYTHON_wrap.cxx: In function ‘PyObject* _wrap_iterator_double_precision_get_native(PyObject*, PyObject*)’:
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/IfcPythonPYTHON_wrap.cxx:7477:58: error: ‘class IfcGeom::Iterator<double>’ has no member named ‘get_native’
       result = (IfcGeom::BRepElement< double > *)(arg1)->get_native();
                                                          ^
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/IfcPythonPYTHON_wrap.cxx: In function ‘void init_ifcopenshell_wrapper()’:
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/IfcPythonPYTHON_wrap.cxx:18011:83: error: ‘TRAVERSE’ is not a member of ‘IfcGeom::IteratorSettings’
   SWIG_Python_SetConstant(d, "settings_TRAVERSE",SWIG_From_int(static_cast< int >(IfcGeom::IteratorSettings::TRAVERSE)));
                                                                                   ^
ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/build.make:62: recipe for target 'ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o' failed
make[2]: *** [ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o] Error 1
make[2]: Leaving directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
CMakeFiles/Makefile2:218: recipe for target 'ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/all' failed
make[1]: *** [ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/all] Error 2
make[1]: Leaving directory '/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build'
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

~~~

**Comment by berndhahnebach** [comment]
> run the command for compiling IfcPythonPYTHON_wrap.cxx but instead add a -E to g++ or alternatively, run cpp instead of g++ to get the preprocessed code.

How does it works?

**Comment by aothms** [comment]
Sorry, for the delay. Has this been resolved somehow? Travis reports the build is fine, so I'm inclined to say it must be something specific to your setup, but I'm fairly clueless what exactly.

The command to compile the wrapper is:

~~~
cd /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap && /usr/bin/c++ 
-DHAVE_ICU -DUSE_IFC2x3 -D_ifcopenshell_wrapper_EXPORTS -O3 -DNDEBUG -fPIC 
-I/usr/local/include/opencascade -I/usr/include/python2.7 
-I/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap -Wall -Wextra 
-fPIC -std=c++11 -o CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o -c 
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/IfcPythonPYTHON_wrap.cxx 
~~~

Perhaps you can change `c++` to `cpp` or use `/usr/bin/c++ -E` to get the preprocessed code in `CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o`. Then copy that here to see if it provides further insights?

**Comment by berndhahnebach** [comment]
Hi Thomas, thanks for the informations. Sorry for posting myself not more informations. Yes, I saw it compiles smooth on travis. What I'm gone do is, trying to compile in a vagrant box. If it works than it's my computer ... But I'm really busy at the moment. I will come back but it could be take a few days ...

BTW: Might be interesting for you. Fabian Gerold has in addition to OpenSceneGraph included support for OpenCascade in his ifcplusplus (https://github.com/ifcquery/ifcplusplus/commits/master)

cheers bernd

**Comment by aothms** [comment]
Any updates on this?

> Fabian Gerold has in addition to OpenSceneGraph included support for OpenCascade in his ifcplusplus

That's at least 4th implementation now for a OCC based IFC geometry kernel. Similar amounts of implementations based on carve. Obviously with all good reasons, but it's a shame we're not able to reduce redundancies.

**Comment by Moult** [comment]
@berndhahnebach hey did you manage to compile since 2017? If so I reckon we can close this :)

**Comment by Moult** [comment]
Closing due to lack of updates.
