### ISSUE TITLE
Broken build after commit a7738ee (Logger updates)

### ISSUE THREAD

**Issue by RickBrice** [IfcOpenShell/IfcOpenShell#8159]
@aothms I'm getting build errors on the v0.8.0 branch. It looks like they come from the subject commit.

Errors are

~~~
5>F:\IfcOpenShell\src\ifcgeom\mapping\IfcCurveSegment.cpp(263,17): error C2065: 'logger_': undeclared identifier
4>F:\IfcOpenShell\src\ifcgeom\mapping\IfcCurveSegment.cpp(263,17): error C2065: 'logger_': undeclared identifier
3>F:\IfcOpenShell\src\ifcgeom\mapping\IfcCurveSegment.cpp(263,17): error C2065: 'logger_': undeclared identifier
5>F:\IfcOpenShell\src\ifcgeom\mapping\IfcCurveSegment.cpp(286,13): error C2065: 'logger_': undeclared identifier
5>F:\IfcOpenShell\src\ifcgeom\mapping\IfcCurveSegment.cpp(324,17): error C2065: 'logger_': undeclared identifier
5>F:\IfcOpenShell\src\ifcgeom\mapping\IfcCurveSegment.cpp(346,13): error C2065: 'logger_': undeclared identifier
~~~

**Comment by RickBrice** [comment]
Fixed in commit 32a601d0

**Comment by aothms** [comment]
Sorry, thanks for the fix, turned out I had more changes open that I forgot to commit.
