### ISSUE TITLE
api.style.edit_surface_style AttributeError: 'Usecase' object has no attribute 'settings'

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#6207]
This error appeared sometime in the last week. This used to be ok:

``` python
import ifcopenshell.api
import bonsai.tool

ifc = bonsai.tool.Ifc.get()

style = ifcopenshell.api.style.add_style(ifc, name="My Style")

ifcopenshell.api.style.add_surface_style(
    ifc,
    style=style,
    ifc_class="IfcSurfaceStyleShading",
    attributes={
        "SurfaceColour": {
            "Name": None,
            "Red": 1.0,
            "Green": 0.8,
            "Blue": 0.4,
        },
        "Transparency": 0.5,
    },
)
```

..but now I get this error:

``` error
  File "/usr/lib64/python3.13/site-packages/ifcopenshell/api/__init__.py", line 253, in wrapper
    result = usecase(*args, **settings)
  File "/usr/lib64/python3.13/site-packages/ifcopenshell/api/style/add_surface_style.py", line 129, in add_surface_style
    ifcopenshell.api.style.edit_surface_style(file, style=style_item, attributes=settings["attributes"])
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/site-packages/ifcopenshell/api/__init__.py", line 253, in wrapper
    result = usecase(*args, **settings)
  File "/usr/lib64/python3.13/site-packages/ifcopenshell/api/style/edit_surface_style.py", line 74, in edit_surface_style
    return usecase.execute(style, attributes)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/site-packages/ifcopenshell/api/style/edit_surface_style.py", line 103, in execute
    setattr(self.settings["style"], key, value)
            ^^^^^^^^^^^^^
AttributeError: 'Usecase' object has no attribute 'settings'
```

**Comment by brunopostle** [comment]
This initially broke with 17642ca, then the error message changed with 174f909

**Comment by Andrej730** [comment]
Fixed after cf1647a451
