### ISSUE TITLE
Conda CI daily build not succeeding often

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#2361]
See https://github.com/IfcOpenShell/IfcOpenShell/actions/workflows/ci-daily-build.yml

with 2/x runs succeeded. Always macos-11-py39?

Maybe due to some conda conflict around lark:

```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/noarch::lark-parser-0.12.0-pyhd8ed1ab_0, conda-forge/noarch::lark-1.1.2-pyhd8ed1ab_0
  path: 'lib/python3.9/site-packages/lark/__pycache__/visitors.cpython-39.pyc'
```

@Krande any ideas?

**Comment by Krande** [comment]
I have noticed it as well. 

Hm, it's difficult to say. The ClobberWarning I believe appears on most (if not all) macOS runtime versions and python versions

![image](https://user-images.githubusercontent.com/9642232/186596949-a94e15c5-4a78-48ef-91bd-707aac750560.png)

![image](https://user-images.githubusercontent.com/9642232/186597011-4c0d21a2-c4ca-44c3-b46e-61ca9d43912d.png)

![image](https://user-images.githubusercontent.com/9642232/186597268-05911641-6335-418c-87a7-e9036a6b04b4.png)

The issue itself seems to be that the test of checking if python can do `import ifcopenshell` results in a `ModuleNotFoundError: No module named 'ifcopenshell'` error. 

I am not sure it is related, but I have observed lately that some Linux agents are randomly killed by lack of VM resources. 

So to eliminate the possibility of this being a result of random VM resource issues I have re-started the last failing macOS-11-py39 job. If the issue prevails, then it is something strange with this particular combination of python and runtime.

I don't really know what the `ClobberWarning` tells us, but as you pointed out, the error refers to the `lark` package. 

I guess if the issue is related to VM resources we might consider reducing the frequency (not on every successful ci.yml run) or perhaps limit to only 1 runtime version? I have noticed that other github action pipelines are often queued due to the resources demanded by the 12 compilations we are doing in parallel. 

Another thing I've noticed slightly related would be if we want to substitute OSX version v10.15 with v12 of macOS. I believe we're seeing some deprecation notices for both osx 10.15 and ubuntu 18.04

![image](https://user-images.githubusercontent.com/9642232/186601263-5010c4e3-df4e-4ad7-a8bb-fae781f9fb47.png)

Anyways, I've restarted the last failing OSX job [here](https://github.com/IfcOpenShell/IfcOpenShell/runs/8010424618?check_suite_focus=true). So I propose if the job passes I think we can blame it on resource limitations of some sort? If it fails again we can dig a bit deeper into what the failing test might be :)

**Comment by Krande** [comment]
The re-run failed with identical error. So I think it is safe to assume it is not related to VM resources. 

Let me know if you think we should consider updating the runtime versions and/or reduce the number of runtime/python versions we test for. 

Meanwhile I guess I will do some research into issues related to conda-build + OSX + py39 and see if the `ClobberWarnings` could be related. A tough one indeed!

**Comment by aothms** [comment]
I see the difference now:

**Failing**

`-- Installing: /usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ifcopenshell/_ifcopenshell_wrapper.so`

**Successful**

`-- Installing: $PREFIX/lib/python3.9/site-packages/ifcopenshell/_ifcopenshell_wrapper.so`

So in the failing case, ifcopenshell is installed in the system interpreter and not into the conda environment.

Later summarized in:

**Failing**

`number of files: 901`

**Successful**

`number of files: 121`

So it seems like the config to cmake is not specific enough? Any ideas?

```
-- Found PythonLibs: /usr/local/Frameworks/Python.framework/Versions/3.10/lib/libpython3.10.dylib (found version "3.10.6") 
-- Found PythonInterp: /usr/local/bin/python3.10 (found version "3.10.6") 
```

---

>  I believe we're seeing some deprecation notices for both osx 10.15 and ubuntu 18.04

I personally believe in selecting the lowest version that works as backwards compatibility (e.g glibc) is generally great.

**Comment by Krande** [comment]
Okay, I think I have a fix for it.

Explicitly setting the path to the python executable worked. See logs below.

I change the build.sh script and explicitly set the python paths instead of using 

```
-DPython3_FIND_STRATEGY=LOCATION \
-DPython3_FIND_FRAMEWORK=NEVER \
```

* Original (failing) -> [GA Fail](https://github.com/Krande/IfcOpenShell/runs/8031375793?check_suite_focus=true)
* Adding `-DPYTHON_EXECUTABLE:FILEPATH=$PYTHON \` -> [GA pass](https://github.com/Krande/IfcOpenShell/runs/8031383809?check_suite_focus=true)
* Adding everything (exec path, include and lib dirs) -> [GA ongoing](https://github.com/Krande/IfcOpenShell/runs/8031383809?check_suite_focus=true)
   `-DPYTHON_EXECUTABLE:FILEPATH=$PYTHON \`
    `-DPYTHON_LIBRARY=$PREFIX/lib \`
   `-DPYTHON_INCLUDE_DIR=$PREFIX/include \` 
   
I can commit directly to master (v0.7.0) branch once the last GA is finished.

**Comment by Krande** [comment]
Fixed by https://github.com/IfcOpenShell/IfcOpenShell/commit/74d730f3688da6c3a32dfdb568e4411a82fa4a6d.

**Comment by aothms** [comment]
Awesome

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op za 27 aug. 2022 08:17 schreef Kristoffer Andersen <
***@***.***>:

**Comment by aothms** [comment]
I see there's indeed some runs still failing I assume due to going out of memory (the schema files take an immense amount of RAM so `ninja` scheduling them optimistically at the same time might be a problem).

Maybe we should try to account for that by limiting the number of concurrent threads in `ninja`. I don't actually know how, but it should be possible by using cmake --build which will translate the --parallel argument to ninja. https://cmake.org/cmake/help/v3.12/release/3.12.html#command-line

**Comment by Krande** [comment]
I am running some tests on my branch with an additional `-j 1` to limit cpu resources during compilation. If the workflow seems more stable (and the run-duration isn't significantly worsened) I can make changes accordingly in the main repo

**Comment by Moult** [comment]
Are these paths intentional? https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/.github/workflows/ci-daily-build.yml#L6-L7

Would it be better to only trigger a build for changes in ifcopenshell-python and the relevant C++ dirs (ifcgeom/ifcparse/etc)? It's a pretty expensive build and commits to ifcdiff/ifcclash/blenderbim/ifcfm/etc probably don't need to trigger it.

**Comment by Krande** [comment]
You're right. Those paths can be significantly narrowed down. I think however we should reduce the triggers for `ci.yml`. 

The "push-path-triggers" related to the daily builds are combined with a specific branch `pr-daily-builds` (which is a branch I used for developing the daily builds). I never changed the branch back, so I think the current trigger for the daily builds is only the successful completion of the `ci.yml` workflow. Which is probably a good thing given that then we know that the c++ code and ifcopenshell-python libraries pass all their tests.

So that means we would limit the `ci.yml` build triggers to something like this:

(Note! I started trying to add all subdirectories relevant for the conda builds, but there might be so many, so I instead went for a "all in, then exclude specific paths" strategy by prepending a `!` in front of the different paths we want to exclude. 


```
on:
  push:
    paths:
      - 'src/**'
      - '!src/blenderbim/**'
      - '!src/ifcdiff/**'
      - '!src/ifcclash/**'
      - '!src/ifcfm/**'
      - '!src/examples/**'
      - 'conda/**'
      - 'cmake/**'
      - '.github/workflows/ci.yml'
  pull_request:
```  

and the `ci-daily-build.yml` to 

```
on:
# Only trigger, when the build workflow succeeded
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
```

Let me know if there are more paths we can safely exclude or if you think it is preferable to explicitly name each path we want to use as a trigger?

**Comment by Moult** [comment]
Those asterisked here are part of the C++ and swig builds I believe: https://github.com/IfcOpenShell/IfcOpenShell#extra-tools so 11 inclusive vs 15 exclusive. It's pretty even (for now?) your call :)

Also maybe derailing the convo but is it possible to rename the workflow files to something a bit more descriptive? I was looking through recently and at first glance got puzzled by cd vs ci vs ci-daily-build vs ci-py-only vs release. (and does release create a deb package? I had no idea!)

**Comment by Krande** [comment]
Nice! That overview helps a lot. I suggest we use that as a source for paths that triggers the `ci.yml`.

Regarding the naming convention (or lack thereof?). I agree. We would probably benefit from improving the names.

For example the `ci-daily-build.yml` could be renamed to `ci-conda-daily-build.yml` 

I am not that familiar with the specific purposes for `ci.yml`, `cd.yml` and `release.yml`, but I see that all 3 compile ifcopenshell and reuses a lot of the same workflow code. So maybe there is some possibility of merging these workflows into 1 and make only the parts that differ conditional?

Also I see that `ci.yml` and `ci-py-only.yml` only differ wrt to a single line -> `-DBUILD_CONVERT=Off \` which exists in the `ci-py-only.yml`. I don't exactly know the background for needing a separate ci for this, but maybe @aothms knows?

**Comment by Krande** [comment]
I just committed https://github.com/IfcOpenShell/IfcOpenShell/commit/87021ebbe7d6d7bafeee78b7f13da2e20f625e7e to remedy the unnecessary triggering of ifcopenshell compilation and conda daily builds

**Comment by aothms** [comment]
> I don't exactly know the background for needing a separate ci for this, but maybe @aothms knows?

It's because there sometimes used to be bugs in the version without IfcConvert (missing serializers, etc.).

There's indeed a lot of overlap between the different workflows. Mostly coming from the fact that they are from different authors and the fact that I'm not really aware how to really parametrize them. 

Some of the differences I'm aware of. `release` only activates on tag. `ci` maybe does a bit more tests and is quicker because it restricts schema versions to 2x3+4. `cd` does the docker and deb package.

Definitely conda is sufficiently different, the rest can probably be merged.

What's the limit on compute resources. Is it a limit per .github workflow script or project?

**Comment by Krande** [comment]
Compute resources from [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) tells us this:

```
Hardware specification for Windows and Linux virtual machines:

2-core CPU (x86_64)
7 GB of RAM
14 GB of SSD space

Hardware specification for macOS virtual machines:

3-core CPU (x86_64)
14 GB of RAM
14 GB of SSD space
```

And the usage limits are (from [here](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits) 20 concurrent jobs (only 5 on OSX) for public projects. 

As discussed earlier, I could try to cap the number of threads used by Ninja to 2 (I think default is 10) for the daily builds of conda. That could potentially reduce the resource demands for what seems to be the heaviest GA workflow. I tried different cpu caps 1, 2 & 4. 1 & 2 passed, while 4 failed. Although I would assume Ninja defaults to the maximum available (so I suspect setting the cap=2 cpus might be what we have today and the passing tests on my branch might just as well have failed).

**Comment by aothms** [comment]
I'm also fine switching to weekly builds for `conda` `release` `cd`. Anyway the wait time is already so long that you're not going to commit and wait for it to be published.

The issue is more about RAM though I think. The schema files are simply very heavy to compile. ninja can look at the number of processor cores available, but can't foresee that a couple of files will take an unreasonable amount of RAM to compile (I think). That's why I'm a little bit confused on whether reducing the amount of workflows running is actually going to make a difference.

**Comment by Krande** [comment]
One observation that puzzles me is that it's only the linux runners that are occasionally terminated abruptly. Windows and OSX seem more stable (only the latter have VM's with more RAM). So it is a bit strange how it's always the Ubuntu based runners that are failing. 

Also, it might be connected with Azure in general seem to be having some capacity issues these days. So the fault might not necessarily lie with the resource demands in our workflows.

Regarding the daily builds I suggest the following. We split the daily builds and the testing of different runtimes into a daily and weekly workflow. 

That means we reduce the number of concurrent runs from 12 to 6 on a daily basis. And once a week we test additional runtimes.

Thoughts?

**Comment by Krande** [comment]
Hey @aothms and @Moult. 

It seems the conda daily build compilation (and conda-forge) of ifcopenshell for `Windows` seem to be failing due to what I believe is due to the dependency update of `boost==1.78.0` from `boost==1.74.0`.

The portion from the log where I first observe the error is

```
[73/872] Building CXX object CMakeFiles\IfcGeom_ifc2x3.dir\C_\Miniconda\envs\conda-build\conda-bld\ifcopenshell_1664218373134\work\src\ifcgeom\IfcGeomIteratorImplementation.cpp.obj
FAILED: CMakeFiles/IfcGeom_ifc2x3.dir/C_/Miniconda/envs/conda-build/conda-bld/ifcopenshell_1664218373134/work/src/ifcgeom/IfcGeomIteratorImplementation.cpp.obj 
C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_CHRONO_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DHAS_SCHEMA_2x3 -DHAS_SCHEMA_4 -DHAS_SCHEMA_4x1 -DHAS_SCHEMA_4x2 -DHAS_SCHEMA_4x3 -DHAS_SCHEMA_4x3_rc1 -DHAS_SCHEMA_4x3_rc2 -DHAS_SCHEMA_4x3_rc3 -DHAS_SCHEMA_4x3_rc4 -DHAVE_NO_DLL -DSCHEMA_SEQ=(2x3)(4)(4x1)(4x2)(4x3_rc1)(4x3_rc2)(4x3_rc3)(4x3_rc4)(4x3) -DUNICODE -DWITH_GLTF -DWITH_HDF5 -DWITH_IFCXML -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -I%PREFIX%\Library\include\opencascade -I%PREFIX%\Library\include\libxml2 -I%PREFIX%\Library\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /O2 /Ob2 /DNDEBUG   -wd4250 -wd4584 -bigobj -W4 -wd4458 -permissive- -DIFC_GEOM_EXPORTS -DIfcSchema=Ifc2x3 -std:c++14 /showIncludes /FoCMakeFiles\IfcGeom_ifc2x3.dir\C_\Miniconda\envs\conda-build\conda-bld\ifcopenshell_1664218373134\work\src\ifcgeom\IfcGeomIteratorImplementation.cpp.obj /FdCMakeFiles\IfcGeom_ifc2x3.dir\IfcGeom_ifc2x3.pdb /FS -c %SRC_DIR%\src\ifcgeom\IfcGeomIteratorImplementation.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
%PREFIX%\Library\include\boost/regex/v5/w32_regex_traits.hpp(200): error C2061: syntax error: identifier 'LCTYPE'
%PREFIX%\Library\include\boost/regex/v5/w32_regex_traits.hpp(217): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
%PREFIX%\Library\include\boost/regex/v5/w32_regex_traits.hpp(217): error C2737: 'boost::re_detail_500::lctype': 'constexpr' object must be initialized
%PREFIX%\Library\include\boost/regex/v5/w32_regex_traits.hpp(217): error C2146: syntax error: missing ';' before identifier 'locale_idefaultansicodepage'
%PREFIX%\Library\include\boost/regex/v5/w32_regex_traits.hpp(220): error C2039: 'LCMapStringA': is not a member of '`global namespace''
```

For full log: https://github.com/IfcOpenShell/IfcOpenShell/actions/runs/3130244395/jobs/5080275801#step:6:877

I guess our two options are either to lock boost to `<= v1.74` or fix whatever has changed in boost in the cpp code. 

FYI: here's the [`boost==1.78 changelog`](https://www.boost.org/users/history/version_1_78_0.html)

Any thoughts?

**Comment by Krande** [comment]
Sure, I see boost v1.79 and v1.80 are both on conda-forge. I can try those 

I also glanced at the boost changelog and saw this
![image](https://user-images.githubusercontent.com/9642232/192697573-fd1efed4-0616-4e0b-96a1-cd1d87b29d74.png)

which might explain the error given that the errors I see in the github actions pipeline are all pointing to a `w32_regex_traits.hpp` file, i.e.:

`%PREFIX%\Library\include\boost/regex/v5/w32_regex_traits.hpp(200): error C2061: syntax error: identifier 'LCTYPE'`

I did take a short stab at looking at the failing cpp file to see if I could follow the import trail and spot any uses of boost::regex that could be directly causing the issue.

The cpp file the compilation fails at is `src\ifcgeom\IfcGeomIteratorImplementation.cpp`  which points to [IteratorImplementation.h](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom_schema_agnostic/IteratorImplementation.h) 

`IteratorImplementation.h` imports boost directly via `#include <boost/function.hpp>` but no uses of boost::regex.

So I followed some of the import-paths and came across this:

`#include "../ifcgeom_schema_agnostic/IfcGeomFilter.h"` which uses `boost::regex` multiple places, like this line [here](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom_schema_agnostic/IfcGeomFilter.h#L85))

I did not find any other occurences of boost::regex, so maybe it's possible to isolate the issue to the `IfcGeomFilter.h` file?

I can give testing boost v 1.80 a try and see if that changes anything. But ideally we would find a solution that works on boost < v1.78 and >v.1.78.

**Comment by aothms** [comment]
> I did not find any other occurences of boost::regex, so maybe it's possible to isolate the issue to the IfcGeomFilter.h file?

The issue is that the error comes from just including the boost regex header, so at that point we're not really using it yet, there isn't anything to correct.

`LCTYPE` and all the missing symbols the boost include talks about are all from Windows.h, e.g https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types So it's definitely related. It's just so confusing to me, why nobody else is running into this issue since we're doing something so basic.

**Comment by Krande** [comment]
Hey @aothms, 

I gave the issues with boost v1.78 and `win32_regex_traits.hpp` a closer look today, and saw that by adding `#include <windows.h>` in .cpp+.h files related to the "win32_regex_traits.hpp" error messages I kept getting I seem to be able to successfully compile everything using boost v1.78.

I don't really know the implications of doing this. But do you think this is something we should consider? Maybe add a flag that this include is only done for boost v1.74+ AND for Windows?

**Comment by aothms** [comment]
@Krande That's a great find.

For me that's good enough of a fix. We have this super nasty include windows.h routine here as well https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcparse/IfcUtil.cpp#L20-L52 Which tries to limit the amount of stuff that gets included (with a lot of potential for name conflicts and increased compile time).

It's also a bit strange though, since it seems to so clearly contradict the change note you listed earlier.

Searching a bit further, we could maybe also `#define BOOST_REGEX_NO_W32` prior to including boost/regex

https://www.boost.org/doc/libs/1_80_0/libs/regex/doc/html/boost_regex/configuration/locale.html

Anyway I would be very happy with any of these changes. Especially also because it would allow us to advance on the vs2022 issue. Feel free to commit sth asap and please send a quick comment when you do so :)

**Comment by Krande** [comment]
Sounds good! 

I'll make a PR out of it asap and we can discuss further any additional flags we might want to add

**Comment by Krande** [comment]
@aothms, now that we've solved the windows and Boost issue we could create a new tag to generate a new conda forge release.

**Comment by aothms** [comment]
Excellent, go ahead @Krande

**Comment by Krande** [comment]
@aothms Hey, the conda builds have been malfunctioning for a while so I thought I should fix them. 

I managed to fix the windows builds, but I am seeing the conda builds for macOS and linux are failing due to the following error related `IfcConnectedFaceSet.cpp`

```
[60/1059] Building CXX object CMakeFiles/IfcGeom_ifc2x3.dir/src/ifcgeom/IfcConnectedFaceSet.cpp.o
FAILED: CMakeFiles/IfcGeom_ifc2x3.dir/src/ifcgeom/IfcConnectedFaceSet.cpp.o 
$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ -DBOOST_ALL_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DHAS_SCHEMA_2x3 -DHAS_SCHEMA_4 -DHAS_SCHEMA_4x1 -DHAS_SCHEMA_4x2 -DHAS_SCHEMA_4x3 -DHAS_SCHEMA_4x3_add1 -DHAS_SCHEMA_4x3_rc1 -DHAS_SCHEMA_4x3_rc2 -DHAS_SCHEMA_4x3_rc3 -DHAS_SCHEMA_4x3_rc4 -DHAS_SCHEMA_4x3_tc1 -DSCHEMA_SEQ="(2x3)(4)(4x1)(4x2)(4x3_rc1)(4x3_rc2)(4x3_rc3)(4x3_rc4)(4x3)(4x3_tc1)(4x3_add1)" -DWITH_GLTF -DWITH_HDF5 -DWITH_IFCXML -I$PREFIX/include/opencascade -I$PREFIX/include/libxml2 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/ifcopenshell-0.7.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -O3 -DNDEBUG   -Wall -Wextra -Wno-maybe-uninitialized -Wno-deprecated-copy -fPIC -DIFC_GEOM_EXPORTS -DIfcSchema=Ifc2x3 -std=gnu++14 -MD -MT CMakeFiles/IfcGeom_ifc2x3.dir/src/ifcgeom/IfcConnectedFaceSet.cpp.o -MF CMakeFiles/IfcGeom_ifc2x3.dir/src/ifcgeom/IfcConnectedFaceSet.cpp.o.d -o CMakeFiles/IfcGeom_ifc2x3.dir/src/ifcgeom/IfcConnectedFaceSet.cpp.o -c $SRC_DIR/src/ifcgeom/IfcConnectedFaceSet.cpp
In file included from $SRC_DIR/src/ifcgeom/IfcConnectedFaceSet.cpp:20:
$SRC_DIR/src/ifcgeom/../ifcgeom_schema_agnostic/base_utils.h:35:40: error: 'gp_GTrsf' does not name a type; did you mean 'gp_Trsf'?
   35 |                 bool is_identity(const gp_GTrsf& t, double tolerance);
      |                                        ^~~~~~~~
      |                                        gp_Trsf
```

Full log -> https://github.com/IfcOpenShell/IfcOpenShell/actions/runs/3909142701/jobs/6679932310#step:6:721

Any idea what it means or where I should start looking?

**Comment by aothms** [comment]
Commit sth, let me know whether that helps

**Comment by Krande** [comment]
It looks like that worked! 

Btw: To limit number the number of unecessary conda build workflows, I just set the daily conda builds on a daily schedule (as opposed to at every completed CI worklow).

**Comment by Krande** [comment]
With the latest fix mentioned in https://github.com/IfcOpenShell/IfcOpenShell/issues/2762#issuecomment-1674662990 I feel comfortable that we can finally close this :)
