### ISSUE TITLE
0.7.0 branch: AttributeError: module 'ifcopenshell.ifcopenshell_wrapper' has no attribute 'settings'

### ISSUE THREAD

**Issue by asctime** [IfcOpenShell/IfcOpenShell#1753]
So after [multiple compiles on the 0.7.0 branch](https://github.com/IfcOpenShell/IfcOpenShell/issues/1725) from #1725 two weeks ago, every application ends with the same error when trying to open the ifcfile (IfcOpenHouse). First saw in FreeCAD and thought it was just an update to the python API over 0.5.0, but also appears when using its own internal viewer:

```
python3 -c "from ifcopenshell.geom.app import application; application().start()"
...
  Max MSAA samples: 16
  Viewport: 476x264
  ResolutionRatio: 1
Traceback (most recent call last):
  File "D:\MSYS2\mingw64\lib\python3.7\site-packages\ifcopenshell\geom\app.py",
line 673, in browse
    self.load(filename)
  File "D:\MSYS2\mingw64\lib\python3.7\site-packages\ifcopenshell\geom\app.py",
line 686, in load
    c.load_file(f, setting=self.settings)
  File "D:\MSYS2\mingw64\lib\python3.7\site-packages\ifcopenshell\geom\app.py",
line 514, in load_file
    setting.set(setting.INCLUDE_CURVES, True)
  File "D:\MSYS2\mingw64\lib\python3.7\site-packages\ifcopenshell\geom\main.py",
 line 72, in set
    ifcopenshell_wrapper.settings.set(self, *args)
AttributeError: module 'ifcopenshell.ifcopenshell_wrapper' has no attribute 'set
tings'
```

And even its included version of blenderbim:
```
Traceback (most recent call last):
  File "D:\MSYS2\mingw64\share\blender\2.82\scripts\addons\blenderbim\bim\operator.py", line 160, in execute
    ifc_importer = import_ifc.IfcImporter(settings)
  File "D:\MSYS2\mingw64\share\blender\2.82\scripts\addons\blenderbim\bim\import_ifc.py", line 172, in __init__
    self.settings_native.set(self.settings_native.INCLUDE_CURVES, True)
  File "D:\MSYS2\mingw64\lib\python3.7\site-packages\ifcopenshell\geom\main.py", line 72, in set
    ifcopenshell_wrapper.settings.set(self, *args)
AttributeError: module 'ifcopenshell.ifcopenshell_wrapper' has no attribute 'settings'
```

Always when loading a file. Same error if using python2 version of the module..
Looking at ifcopenshell_wrapper.py itself I see (and can call) classes for ElementSettings and IteratorSettings but I dont see an implementation for just a plain "settings" class anywhere. Possible swig misfire?

**Comment by aothms** [comment]
Thanks. This was renamed in swig, but not propagated in all places https://github.com/IfcOpenShell/IfcOpenShell/commit/34fd95901137ff023926624e6984b4d7c3c092e4#diff-f1c6238fcd72469c55317acb210f15df2ab55170dd19a5701b21e3226bdfd18bR60

It's specific to having pythonOCC installed and apparently the tests didn't catch that yet.

**Comment by spl1inter** [comment]
Thanks for looking into this again. I notice that line 72 (where the crash is actually triggered) remains unchanged though.. and the same crash still occurs:
```
Traceback (most recent call last):
  File "D:\MSYS2\mingw64\lib\python3.7\site-packages\ifcopenshell\geom\app.py",
line 673, in browse
    self.load(filename)
  File "D:\MSYS2\mingw64\lib\python3.7\site-packages\ifcopenshell\geom\app.py",
line 686, in load
    c.load_file(f, setting=self.settings)
  File "D:\MSYS2\mingw64\lib\python3.7\site-packages\ifcopenshell\geom\app.py",
line 514, in load_file
    setting.set(setting.INCLUDE_CURVES, True)
  File "D:\MSYS2\mingw64\lib\python3.7\site-packages\ifcopenshell\geom\main.py",
 line 72, in set
    ifcopenshell_wrapper.settings.set(self, *args)
AttributeError: module 'ifcopenshell.ifcopenshell_wrapper' has no attribute 'set
tings'
```

Actually I already tried something like your patch for line 72 and ran into this next problem: Using the same class solution as your patch..
                self.use_python_opencascade = value
            else:
                ifcopenshell_wrapper.SerializerSettings.set(self, *args)


Now open file with viewer I get an immediate crash:
```
...
  Max MSAA samples: 16
  Viewport: 476x264
  ResolutionRatio: 1
property set dictionary has 0 entries

```

**Comment by aothms** [comment]
@spl1inter sorry for the late reply. My message was unclear. I was pointing to the commit that caused the issue, the commit changing line 72 was listed above my comment https://github.com/IfcOpenShell/IfcOpenShell/commit/da8e3e628883dbfd53d8fb05a27674035aaf569f

@CyrilWaechter strange. What does the following look like on your interpreter:

```
>>> import ifcopenshell
>>> ifcopenshell.version
'v0.7.0-768b754a'
>>> ifcopenshell.ifcopenshell_wrapper.SerializerSettings
<class 'ifcopenshell.ifcopenshell_wrapper.SerializerSettings'>
```

**Comment by CyrilWaechter** [comment]
@aothms I found out the issue. A symlink was interfering. So it is unrelated. Sorry.

**Comment by Moult** [comment]
Seems to be fixed.
